// -------------------------------------------------------------------------
// Copyright (C) 2024 Fernando López Laso - All Rights Reserved
//
// Unauthorized copying of this file, via any medium is strictly prohibited.
// This file is confidential and only available to authorized individuals
// with the permission of the copyright holders.
// -------------------------------------------------------------------------

use std::fmt;

#[derive(Debug)]
pub enum IconMoon {
    Home,
    Enter,
    PreviousPage,
    NextPage,
    Bookmark,
    Menu,
    PrintScreen,
    Link,
    Anchor,
    Label,
    Key,
    Lock,
    LockOpen,
    Shield,
    ShieldWithCross,
    Pencil,
    Pen,
    Paperclip,
    Envelope,
    FourCorners,
    GearNoHub,
    GarbageCan,
    Newspaper,
    CalendarMonth,
    CalendarDay,
    Bell,
    Forbidden,
    NoEntry,
    Contrast,
    Brightness,
    GlobeMeridians,
    Bullseye,
    Alarm,
    MoneyBag,
    Banknote,
    CurrencyExchange,
    Droplet,
    Film,
    ElectricCord,
    Warning,
    Bolt,
    Fireworks,
    AnimalBug,
    Crown,
    Folder,
    FolderOpen,
    File,
    FileText,
    FileImage,
    Picture,
    Copy,
    Scissors,
    Clipboard,
    Addressbook,
    Notebook,
    PhoneReceiver,
    Bullhorn,
    Book,
    BookOpen,
    Books,
    Creditcard,
    Notepad,
    At,
    StackWindow,
    MaximizeWindow,
    Minimize,
    Cancel,
    Check,
    CheckboxChecked,
    CheckboxPartial,
    CheckboxUnchecked,
    Square,
    Hexagon,
    Pentagon,
    RadioChecked,
    Circle,
    CircleOpen,
    Battery,
    Cabinet,
    FontSize,
    Palette,
    Lightbulb,
    Pill,
    Syringe,
    Fire,
    Explosion,
    Database,
    Suitcase,
    Inbox,
    Outbox,
    SearchRight,
    SearchLeft,
    VolumeMute,
    Volume,
    VolumeLow,
    VolumeHigh,
    Flag,
    FlagOpen,
    FlagCheckered,
    RotateCw,
    RotateCcwSide,
    RotateCcw,
    RotateCwSide,
    Loop,
    LoopAlt,
    Shuffle,
    ArrowForward,
    ArrowUndo,
    ArrowReply,
    ArrowRedo,
    ArrowLeftRight,
    ArrowUpDown,
    CaretLeft,
    CaretUp,
    CaretRight,
    CaretDown,
    CircleArrowLeft,
    CircleArrowUp,
    CircleArrowRight,
    CircleArrowDown,
    ArrowRight,
    ArrowDownRight,
    ArrowDown,
    ArrowDownLeft,
    ArrowLeft,
    ArrowUpLeft,
    ArrowUp,
    ArrowUpRight,
    ThumbsDown,
    ThumbsUp,
    PointLeft,
    PointDown,
    PointRight,
    PointUp,
    Plus,
    Minus,
    Multiply,
    Divide,
    Eject,
    First,
    Backward,
    Play,
    Forward,
    Last,
    Pause,
    Stop,
    Record,
    GenderFemale,
    GenderMale,
    GenderTransgender,
    GenderNonBinary,
    GenderMaleFemale,
    GenderFemaleFemale,
    GenderMaleMale,
    SquareMinus,
    SquarePlus,
    Smiley,
    SmileyHappy,
    SmileyGrin,
    SmileyCool,
    SmileySad,
    SmileyEvil,
    CurrencyEuro,
    CurrencyPound,
    CurrencyDollar,
    Yen,
    PeaceDove,
    Bouquet,
    StarShooting,
    Ring,
    Close,
    Moon,
    MoonFull,
    MoonFirstQuarter,
    MoonWaxingGibbous,
    MoonWaningCrescent,
    MoonWaxingCrescent,
    MoonWaningGibbous,
    MoonLastQuarter,
    MoonNew,
    WaterWave,
    Kiss,
    Diamond,
    Mushroom,
    StarCircled,
    SpeechBubble,
    Smoking,
    SmokingForbidden,
    Church,
    ConvenienceStore,
    School,
    Hotel,
    Building,
    Factory,
    Castle,
    Circus,
    Tent,
    FuelPump,
    Airplane,
    Globe2,
    Fountain,
    LeftLuggage,
    Beach,
    WorldMap,
    Balloon,
    PerformingArts,
    FerrisWheel,
    Rollercoaster,
    SlotMachine,
    Cinema,
    FilmReel,
    Die,
    Ticket,
    Tennis,
    FootballSoccer,
    Baseball,
    FootballAmerican,
    Billiards,
    Bowling,
    MedalMilitary,
    MedalSports,
    Trophy,
    MusicQuarterNote,
    MusicEighthNote,
    MusicEigthNotes,
    MusicSixteenthNotes,
    GClef,
    Piano,
    MusicViolin,
    Guitar,
    Saxophone,
    MusicTrumpet,
    Sandals,
    HighHeeledShoes,
    OutfitNecktie,
    OutfitShirt,
    OutfitDress,
    OutfitBikini,
    Handbag,
    Purse,
    Lipstick,
    Sushi,
    RiceBall,
    ChickenLeg,
    Lollipop,
    Candy,
    Donut,
    Fries,
    Cooking,
    DrinkCoffee,
    SteamingBowl,
    FoodRice,
    PotFood,
    FoodSpaghetti,
    FoodChicken,
    FoodHamburger,
    Cake,
    Bread,
    Lemon,
    Apple,
    Pear,
    Tomato3,
    Grapes,
    FoodPizza,
    Gingerbread,
    FoodIceCream,
    DrinkTropical,
    DrinkCocktail,
    DrinkBeer,
    DrinkWine,
    PieChartReverse,
    PieChart,
    Chart,
    ChartUp,
    ChartDown,
    ChartLine,
    Bank,
    Movie,
    Motorbike,
    CarFront,
    BusFront,
    Bicycle,
    Car,
    Bus,
    Truck,
    Rocket,
    Telescope,
    SatelliteDisk,
    Dna,
    Microscope,
    Chair,
    Monitor,
    PhoneMobile,
    PcDesktop,
    PcOld,
    Laptop,
    ComputerNetwork,
    HardDisk,
    Television,
    Pager,
    Projector,
    PhotoCameraFlash,
    PhotoCamera,
    VideoCamera,
    CameraMovie,
    MusicPlayer,
    Radio,
    Phone,
    Printer,
    Tape,
    Mouse,
    Videogame,
    Joystick,
    Keyboard,
    KeyboardWireless,
    Floppy,
    Disk,
    Headphone,
    Calculator,
    AnimalGoat,
    AnimalBactrianCamel,
    AnimalDromedaryCamel,
    AnimalCow,
    AnimalHorse,
    AnimalCat,
    AnimalRabbit,
    AnimalRooster,
    AnimalPig,
    AnimalDolphin,
    Snake,
    AnimalSnail,
    BlackFlorette,
    Florette,
    Flower,
    ChristmasTree,
    TreePine,
    Tree,
    TreePalm,
    Cactus,
    Herb,
    Leaf,
    MapleLeaf,
    Spider,
    AnimalAnt,
    Spider7Web,
    PawPrints,
    Footprints,
    Pedestrian,
    Dancing,
    Swimming,
    Weighlifting,
    IceSkater,
    Skier,
    Snowboarding,
    Running,
    Bicyclist,
    Wheelchair,
    Restroom,
    WomanAndWoman,
    ManAndWoman,
    ManAndMan,
    Family,
    Baby,
    Eye,
    Ear,
    Hand,
    HandFist,
    User,
    Users,
    ConstructionWorker,
    PassportControl,
    Guard,
    Spy,
    FaceMan,
    FaceWoman,
    FaceBoy,
    FaceGirl,
    FaceBaby,
    FaceCallcenter,
    FacePrincess,
    FaceOldChineseMan,
    FaceManWithTurban,
    FaceSantaClaus,
    Snowman,
    Panda,
    FaceKitty,
    Imp,
    FaceMonkey,
    FaceBear,
    FaceHamster,
    FaceChihuahua,
    Alien,
    Skull,
    Ghost,
    Comet,
    StarEightPoints,
    Snowflake,
    Rainbow,
    Sun,
    Star,
    StarOpen,
    AceOfDiamonds,
    AceOfClubs,
    AceOfSpades,
    AceOfHearts,
    Diamonds,
    Clubs,
    Spades,
    Heart,
    HeartBroken,
    HeartBeating,
    HeartRibbon,
    HeartOpen,
    HeartTilted,
    Hearts,
    HeartWithArrow,
    Clock,
    Stopwatch,
    Watch,
    Target,
    EnvelopeStamped,
    PhoneLocation,
    Graduation,
    Gift,
    Tophat,
    Eyeglasses,
    Sunglasses,
    JackOLantern,
    Umbrella,
    Headstone,
    Death,
    SkullAndBones,
    Coffin,
    Bomb,
    Helm,
    Crosshairs,
    TrafficLight,
    Candle,
    BabyBottle,
    Pushpin,
    Microphone,
    Flashlight,
    KeyAlt,
    Dagger,
    Pistol,
    Pick,
    Wrench,
    Hammer,
    Ruler2,
    Ruler,
    Hourglass,
    Knife,
    ForkKnife,
    ForkKnifePlate,
    NutAndBolt,
    Gear,
    HammerWrench,
    HammerAndPick,
    CrossedSwords,
    PermanentPaper,
    Infinity,
    Command,
    Retrograde,
    Aleph,
    Omega,
    Registered,
    Copyright,
    AtSymbol,
    QuestionMark,
    ExclamationMark,
    BraceLeft,
    BraceRight,
    ParenthesisLeft,
    ParenthesisRight,
    SquareBracketLeft,
    SquareBracketRight,
    Percent,
    Perthousand,
    Ampersand,
    AsteriskFive,
    Number,
    AsteriskSix,
    Scales,
    Recycle,
    Chessboard,
    ChessWhitePawn,
    ChessBlackPawn,
    ChessWhiteKnight,
    ChessBlackKnight,
    ChessWhiteBishop,
    ChessBlackBishop,
    ChessWhiteRook,
    ChessBlackRook,
    ChessWhiteQueen,
    ChessWhiteKing,
    ChessBlackKing,
    ChessBlackQueen,
    CrossPommee,
    Cloud,
    CrossOfJerusalem,
    MalteseCross,
    CrossOrthodox,
    ChiRho,
    Ankh,
    LatinCross,
    LatinCrossOutline,
    CelticCross,
    CrossOfLorraine,
    StarOfDavid,
    StarAndCrescent,
    Farsi,
    Khanda,
    Temple,
    Peace,
    Shamrock,
    FourLeafClover,
    WheelOfDharma,
    Om,
    SwastikaRight,
    SwastikaLeft,
    Pentagram,
    PentagramInverted,
    Radiation,
    Biohazard,
    Atom,
    Caduceus,
    Asclepius,
    HammerSickle,
    Tao,
    FleurDeLis,
    DigitZero,
    DigitOne,
    DigitTwo,
    DigitThree,
    DigitFour,
    DigitFive,
    DigitSix,
    DigitSeven,
    DigitEight,
    DigitNine,
    Lettera,
    Letterb,
    Letterc,
    Letterd,
    Lettere,
    Letterf,
    Letterg,
    Letterh,
    Letteri,
    Letterj,
    Letterk,
    Letterl,
    Letterm,
    Lettern,
    Lettero,
    Letterp,
    Letterq,
    Letterr,
    Letters,
    Lettert,
    Letteru,
    Letterv,
    Letterw,
    Letterx,
    Lettery,
    Letterz,
    LetterA,
    LetterB,
    LetterC,
    LetterD,
    LetterE,
    LetterF,
    LetterG,
    LetterH,
    LetterI,
    LetterJ,
    LetterK,
    LetterL,
    LetterM,
    LetterN,
    LetterO,
    LetterP,
    LetterQ,
    LetterR,
    LetterS,
    LetterT,
    LetterU,
    LetterV,
    LetterW,
    LetterX,
    LetterY,
    LetterZ,
    WebTwitter,
    WebFacebook,
    WebTumblr,
    WebLinkedin,
    WebGoogleplus,
    Youtube,
    WebStumbleupon,
    WebBehance,
    WebMixi,
    WebDelicious,
    WebSinaWeibo,
    WebPicassa,
    WebPicasa,
    WebLastfm,
    WebSpotify,
    WebJoomla,
    Vk,
    WebYelp,
    WebVine,
    WebRdio,
    WebSoundcloud,
    Lastfm,
    WebFoursquare,
    WebVimeo,
    WebCircles,
    WebPinterest,
    Digg,
    WebFlattr,
    WebInstagram,
    WebRenren,
    WebFlickr,
    WebDribbble,
    WebDeviantart,
    WebForrst,
    WebStackoverflow,
    WebGithub,
    WebGit,
    WebReddit,
    WebPaypal,
    WebSkype,
    WebVk,
    WebGoogleDrive,
    WebQq,
    WebDropbox,
    WebSteam,
    WebEvernote,
    WebSmashing,
    WebBlogger,
    WebWordpress,
    WebDrupal,
    BrowserChrome,
    BrowserIe,
    BrowserSafari,
    BrowserFirefox,
    BrowserOpera,
    OsAndroid,
    OsWindows,
    OsApple,
    Linux,
}

impl fmt::Display for IconMoon {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl IconMoon {
    pub fn as_str(&self) -> &'static str {
        match self {
            IconMoon::Home => "\u{1f3e0}",
            IconMoon::Enter => "\u{2386}",
            IconMoon::PreviousPage => "\u{2397}",
            IconMoon::NextPage => "\u{2398}",
            IconMoon::Bookmark => "\u{1f516}",
            IconMoon::Menu => "\u{2630}",
            IconMoon::PrintScreen => "\u{2399}",
            IconMoon::Link => "\u{1f517}",
            IconMoon::Anchor => "\u{2693}",
            IconMoon::Label => "\u{1f3f7}",
            IconMoon::Key => "\u{1f511}",
            IconMoon::Lock => "\u{1f50f}",
            IconMoon::LockOpen => "\u{1f513}",
            IconMoon::Shield => "\u{1f6e1}",
            IconMoon::ShieldWithCross => "\u{26e8}",
            IconMoon::Pencil => "\u{270f}",
            IconMoon::Pen => "\u{1f58a}",
            IconMoon::Paperclip => "\u{1f4ce}",
            IconMoon::Envelope => "\u{2709}",
            IconMoon::FourCorners => "\u{26f6}",
            IconMoon::GearNoHub => "\u{26ed}",
            IconMoon::GarbageCan => "\u{1f5d1}",
            IconMoon::Newspaper => "\u{1f4f0}",
            IconMoon::CalendarMonth => "\u{1f4c5}",
            IconMoon::CalendarDay => "\u{1f4c6}",
            IconMoon::Bell => "\u{1f514}",
            IconMoon::Forbidden => "\u{1f6ab}",
            IconMoon::NoEntry => "\u{26d4}",
            IconMoon::Contrast => "\u{25d1}",
            IconMoon::Brightness => "\u{1f506}",
            IconMoon::GlobeMeridians => "\u{1f310}",
            IconMoon::Bullseye => "\u{25ce}",
            IconMoon::Alarm => "\u{23f0}",
            IconMoon::MoneyBag => "\u{1f4b0}",
            IconMoon::Banknote => "\u{1f4b5}",
            IconMoon::CurrencyExchange => "\u{1f4b1}",
            IconMoon::Droplet => "\u{1f4a7}",
            IconMoon::Film => "\u{1f39e}",
            IconMoon::ElectricCord => "\u{1f50c}",
            IconMoon::Warning => "\u{26a0}",
            IconMoon::Bolt => "\u{26a1}",
            IconMoon::Fireworks => "\u{1f386}",
            IconMoon::AnimalBug => "\u{1f41b}",
            IconMoon::Crown => "\u{1f451}",
            IconMoon::Folder => "\u{1f5c0}",
            IconMoon::FolderOpen => "\u{1f5c1}",
            IconMoon::File => "\u{1f5cb}",
            IconMoon::FileText => "\u{1f5b9}",
            IconMoon::FileImage => "\u{1f5bb}",
            IconMoon::Picture => "\u{1f5bc}",
            IconMoon::Copy => "\u{1f5d0}",
            IconMoon::Scissors => "\u{2702}",
            IconMoon::Clipboard => "\u{1f4cb}",
            IconMoon::Addressbook => "\u{1f4d2}",
            IconMoon::Notebook => "\u{1f4d3}",
            IconMoon::PhoneReceiver => "\u{1f4de}",
            IconMoon::Bullhorn => "\u{1f56b}",
            IconMoon::Book => "\u{1f4d5}",
            IconMoon::BookOpen => "\u{1f4d6}",
            IconMoon::Books => "\u{1f4da}",
            IconMoon::Creditcard => "\u{1f4b3}",
            IconMoon::Notepad => "\u{1f5ca}",
            IconMoon::At => "\u{ff3c}",
            IconMoon::StackWindow => "\u{ff33}",
            IconMoon::MaximizeWindow => "\u{1f5d6}",
            IconMoon::Minimize => "\u{1f5d5}",
            IconMoon::Cancel => "\u{1f5d9}",
            IconMoon::Check => "\u{2714}",
            IconMoon::CheckboxChecked => "\u{2611}",
            IconMoon::CheckboxPartial => "\u{25a3}",
            IconMoon::CheckboxUnchecked => "\u{2610}",
            IconMoon::Square => "\u{25a0}",
            IconMoon::Hexagon => "\u{2b23}",
            IconMoon::Pentagon => "\u{2b1f}",
            IconMoon::RadioChecked => "\u{1f518}",
            IconMoon::Circle => "\u{23fa}",
            IconMoon::CircleOpen => "\u{25cb}",
            IconMoon::Battery => "\u{1f50b}",
            IconMoon::Cabinet => "\u{1f5c4}",
            IconMoon::FontSize => "\u{1f5db}",
            IconMoon::Palette => "\u{1f3a8}",
            IconMoon::Lightbulb => "\u{1f4a1}",
            IconMoon::Pill => "\u{1f48a}",
            IconMoon::Syringe => "\u{1f489}",
            IconMoon::Fire => "\u{1f525}",
            IconMoon::Explosion => "\u{1f4a5}",
            IconMoon::Database => "\u{26c3}",
            IconMoon::Suitcase => "\u{1f4bc}",
            IconMoon::Inbox => "\u{1f4e5}",
            IconMoon::Outbox => "\u{1f4e4}",
            IconMoon::SearchRight => "\u{1f50e}",
            IconMoon::SearchLeft => "\u{1f50d}",
            IconMoon::VolumeMute => "\u{1f3e1}",
            IconMoon::Volume => "\u{1f508}",
            IconMoon::VolumeLow => "\u{1f509}",
            IconMoon::VolumeHigh => "\u{1f50a}",
            IconMoon::Flag => "\u{2691}",
            IconMoon::FlagOpen => "\u{2690}",
            IconMoon::FlagCheckered => "\u{1f3c1}",
            IconMoon::RotateCw => "\u{21bb}",
            IconMoon::RotateCcwSide => "\u{27f3}",
            IconMoon::RotateCcw => "\u{21ba}",
            IconMoon::RotateCwSide => "\u{27f2}",
            IconMoon::Loop => "\u{1f501}",
            IconMoon::LoopAlt => "\u{1f503}",
            IconMoon::Shuffle => "\u{1f500}",
            IconMoon::ArrowForward => "\u{2ba9}",
            IconMoon::ArrowUndo => "\u{2baa}",
            IconMoon::ArrowReply => "\u{2ba8}",
            IconMoon::ArrowRedo => "\u{2bab}",
            IconMoon::ArrowLeftRight => "\u{2b0c}",
            IconMoon::ArrowUpDown => "\u{2b0d}",
            IconMoon::CaretLeft => "\u{23f4}",
            IconMoon::CaretUp => "\u{23f6}",
            IconMoon::CaretRight => "\u{23f5}",
            IconMoon::CaretDown => "\u{23f7}",
            IconMoon::CircleArrowLeft => "\u{2b88}",
            IconMoon::CircleArrowUp => "\u{2b89}",
            IconMoon::CircleArrowRight => "\u{2b8a}",
            IconMoon::CircleArrowDown => "\u{2b8b}",
            IconMoon::ArrowRight => "\u{27a1}",
            IconMoon::ArrowDownRight => "\u{2b0a}",
            IconMoon::ArrowDown => "\u{2b07}",
            IconMoon::ArrowDownLeft => "\u{2b0b}",
            IconMoon::ArrowLeft => "\u{2b05}",
            IconMoon::ArrowUpLeft => "\u{2b09}",
            IconMoon::ArrowUp => "\u{2b06}",
            IconMoon::ArrowUpRight => "\u{2b08}",
            IconMoon::ThumbsDown => "\u{1f44e}",
            IconMoon::ThumbsUp => "\u{1f44d}",
            IconMoon::PointLeft => "\u{261c}",
            IconMoon::PointDown => "\u{261f}",
            IconMoon::PointRight => "\u{261e}",
            IconMoon::PointUp => "\u{261d}",
            IconMoon::Plus => "\u{271a}",
            IconMoon::Minus => "\u{2796}",
            IconMoon::Multiply => "\u{2716}",
            IconMoon::Divide => "\u{2797}",
            IconMoon::Eject => "\u{23cf}",
            IconMoon::First => "\u{23ee}",
            IconMoon::Backward => "\u{23ea}",
            IconMoon::Play => "\u{25b6}",
            IconMoon::Forward => "\u{23e9}",
            IconMoon::Last => "\u{23ed}",
            IconMoon::Pause => "\u{23f8}",
            IconMoon::Stop => "\u{23f9}",
            IconMoon::Record => "\u{2609}",
            IconMoon::GenderFemale => "\u{2640}",
            IconMoon::GenderMale => "\u{2642}",
            IconMoon::GenderTransgender => "\u{26a6}",
            IconMoon::GenderNonBinary => "\u{26a7}",
            IconMoon::GenderMaleFemale => "\u{26a4}",
            IconMoon::GenderFemaleFemale => "\u{26a2}",
            IconMoon::GenderMaleMale => "\u{26a3}",
            IconMoon::SquareMinus => "\u{229f}",
            IconMoon::SquarePlus => "\u{229e}",
            IconMoon::Smiley => "\u{263a}",
            IconMoon::SmileyHappy => "\u{1f603}",
            IconMoon::SmileyGrin => "\u{1f604}",
            IconMoon::SmileyCool => "\u{1f60e}",
            IconMoon::SmileySad => "\u{2639}",
            IconMoon::SmileyEvil => "\u{1f608}",
            IconMoon::CurrencyEuro => "\u{20ac}",
            IconMoon::CurrencyPound => "\u{ffe1}",
            IconMoon::CurrencyDollar => "\u{ff04}",
            IconMoon::Yen => "\u{ffe5}",
            IconMoon::PeaceDove => "\u{1f54a}",
            IconMoon::Bouquet => "\u{1f490}",
            IconMoon::StarShooting => "\u{1f320}",
            IconMoon::Ring => "\u{1f48d}",
            IconMoon::Close => "\u{2297}",
            IconMoon::MoonFull => "\u{1f315}",
            IconMoon::MoonFirstQuarter => "\u{1f313}",
            IconMoon::MoonWaxingGibbous => "\u{1f314}",
            IconMoon::MoonWaningCrescent => "\u{1f318}",
            IconMoon::MoonWaxingCrescent => "\u{1f312}",
            IconMoon::MoonWaningGibbous => "\u{1f316}",
            IconMoon::MoonLastQuarter => "\u{1f317}",
            IconMoon::MoonNew => "\u{1f311}",
            IconMoon::Moon => "\u{1f319}",
            IconMoon::WaterWave => "\u{1f30a}",
            IconMoon::Kiss => "\u{1f48b}",
            IconMoon::Diamond => "\u{1f48e}",
            IconMoon::Mushroom => "\u{1f344}",
            IconMoon::StarCircled => "\u{272a}",
            IconMoon::SpeechBubble => "\u{1f4ac}",
            IconMoon::Smoking => "\u{1f6ac}",
            IconMoon::SmokingForbidden => "\u{1f6ad}",
            IconMoon::Church => "\u{26ea}",
            IconMoon::ConvenienceStore => "\u{1f3ea}",
            IconMoon::School => "\u{1f3eb}",
            IconMoon::Hotel => "\u{1f3e8}",
            IconMoon::Building => "\u{1f3e2}",
            IconMoon::Factory => "\u{1f3ed}",
            IconMoon::Castle => "\u{1f3f0}",
            IconMoon::Circus => "\u{1f3aa}",
            IconMoon::Tent => "\u{26fa}",
            IconMoon::FuelPump => "\u{26fd}",
            IconMoon::Airplane => "\u{2708}",
            IconMoon::Globe2 => "\u{1f30d}",
            IconMoon::Fountain => "\u{26f2}",
            IconMoon::LeftLuggage => "\u{1f6c5}",
            IconMoon::Beach => "\u{26f1}",
            IconMoon::WorldMap => "\u{1f5fa}",
            IconMoon::Balloon => "\u{1f388}",
            IconMoon::PerformingArts => "\u{1f3ad}",
            IconMoon::FerrisWheel => "\u{1f3a1}",
            IconMoon::Rollercoaster => "\u{1f3a2}",
            IconMoon::SlotMachine => "\u{1f3b0}",
            IconMoon::Cinema => "\u{1f3a6}",
            IconMoon::FilmReel => "\u{2707}",
            IconMoon::Die => "\u{1f3b2}",
            IconMoon::Ticket => "\u{1f39f}",
            IconMoon::Tennis => "\u{1f3be}",
            IconMoon::FootballSoccer => "\u{26bd}",
            IconMoon::Baseball => "\u{26be}",
            IconMoon::FootballAmerican => "\u{1f3c8}",
            IconMoon::Billiards => "\u{1f3b1}",
            IconMoon::Bowling => "\u{1f3b3}",
            IconMoon::MedalMilitary => "\u{1f396}",
            IconMoon::MedalSports => "\u{1f3c5}",
            IconMoon::Trophy => "\u{1f3c6}",
            IconMoon::MusicQuarterNote => "\u{2669}",
            IconMoon::MusicEighthNote => "\u{266a}",
            IconMoon::MusicEigthNotes => "\u{266b}",
            IconMoon::MusicSixteenthNotes => "\u{266c}",
            IconMoon::GClef => "\u{1d11e}",
            IconMoon::Piano => "\u{1f3b9}",
            IconMoon::MusicViolin => "\u{1f3bb}",
            IconMoon::Guitar => "\u{1f3b8}",
            IconMoon::Saxophone => "\u{1f3b7}",
            IconMoon::MusicTrumpet => "\u{1f3ba}",
            IconMoon::Sandals => "\u{1f461}",
            IconMoon::HighHeeledShoes => "\u{1f460}",
            IconMoon::OutfitNecktie => "\u{1f454}",
            IconMoon::OutfitShirt => "\u{1f455}",
            IconMoon::OutfitDress => "\u{1f457}",
            IconMoon::OutfitBikini => "\u{1f459}",
            IconMoon::Handbag => "\u{1f45c}",
            IconMoon::Purse => "\u{1f45b}",
            IconMoon::Lipstick => "\u{1f484}",
            IconMoon::Sushi => "\u{1f363}",
            IconMoon::RiceBall => "\u{1f359}",
            IconMoon::ChickenLeg => "\u{1f357}",
            IconMoon::Lollipop => "\u{1f36d}",
            IconMoon::Candy => "\u{1f36c}",
            IconMoon::Donut => "\u{1f369}",
            IconMoon::Fries => "\u{1f35f}",
            IconMoon::Cooking => "\u{1f373}",
            IconMoon::DrinkCoffee => "\u{2615}",
            IconMoon::SteamingBowl => "\u{1f35c}",
            IconMoon::FoodRice => "\u{1f35a}",
            IconMoon::PotFood => "\u{1f372}",
            IconMoon::FoodSpaghetti => "\u{1f35d}",
            IconMoon::FoodChicken => "\u{1f414}",
            IconMoon::FoodHamburger => "\u{1f354}",
            IconMoon::Cake => "\u{1f382}",
            IconMoon::Bread => "\u{1f35e}",
            IconMoon::Lemon => "\u{1f34b}",
            IconMoon::Apple => "\u{1f34e}",
            IconMoon::Pear => "\u{1f350}",
            IconMoon::Tomato3 => "\u{1f345}",
            IconMoon::Grapes => "\u{1f347}",
            IconMoon::FoodPizza => "\u{1f355}",
            IconMoon::Gingerbread => "\u{1f36a}",
            IconMoon::FoodIceCream => "\u{1f368}",
            IconMoon::DrinkTropical => "\u{1f379}",
            IconMoon::DrinkCocktail => "\u{1f378}",
            IconMoon::DrinkBeer => "\u{1f37a}",
            IconMoon::DrinkWine => "\u{1f377}",
            IconMoon::PieChartReverse => "\u{25d4}",
            IconMoon::PieChart => "\u{25d5}",
            IconMoon::Chart => "\u{1f4ca}",
            IconMoon::ChartUp => "\u{1f4c8}",
            IconMoon::ChartDown => "\u{1f4c9}",
            IconMoon::ChartLine => "\u{1f5e0}",
            IconMoon::Bank => "\u{1f3e6}",
            IconMoon::Movie => "\u{1f3ac}",
            IconMoon::Motorbike => "\u{1f3cd}",
            IconMoon::CarFront => "\u{1f698}",
            IconMoon::BusFront => "\u{1f68d}",
            IconMoon::Bicycle => "\u{1f6b2}",
            IconMoon::Car => "\u{1f697}",
            IconMoon::Bus => "\u{1f68c}",
            IconMoon::Truck => "\u{1f69a}",
            IconMoon::Rocket => "\u{1f680}",
            IconMoon::Telescope => "\u{1f52d}",
            IconMoon::SatelliteDisk => "\u{1f4e1}",
            IconMoon::Dna => "\u{26d3}",
            IconMoon::Microscope => "\u{1f52c}",
            IconMoon::Chair => "\u{1f4ba}",
            IconMoon::Monitor => "\u{1f5b5}",
            IconMoon::PhoneMobile => "\u{1f4f1}",
            IconMoon::PcDesktop => "\u{1f5a5}",
            IconMoon::PcOld => "\u{1f5b3}",
            IconMoon::Laptop => "\u{1f4bb}",
            IconMoon::ComputerNetwork => "\u{1f5a7}",
            IconMoon::HardDisk => "\u{1f5b4}",
            IconMoon::Television => "\u{1f4fa}",
            IconMoon::Pager => "\u{1f4df}",
            IconMoon::Projector => "\u{1f4fd}",
            IconMoon::PhotoCameraFlash => "\u{1f4f8}",
            IconMoon::PhotoCamera => "\u{1f4f7}",
            IconMoon::VideoCamera => "\u{1f4f9}",
            IconMoon::CameraMovie => "\u{1f3a5}",
            IconMoon::MusicPlayer => "\u{1f4fe}",
            IconMoon::Radio => "\u{1f4fb}",
            IconMoon::Phone => "\u{260e}",
            IconMoon::Printer => "\u{1f5b6}",
            IconMoon::Tape => "\u{1f5ad}",
            IconMoon::Mouse => "\u{1f5b1}",
            IconMoon::Videogame => "\u{1f3ae}",
            IconMoon::Joystick => "\u{1f579}",
            IconMoon::Keyboard => "\u{1f5ae}",
            IconMoon::KeyboardWireless => "\u{2328}",
            IconMoon::Floppy => "\u{1f4be}",
            IconMoon::Disk => "\u{1f4bf}",
            IconMoon::Headphone => "\u{1f3a7}",
            IconMoon::Calculator => "\u{1f5a9}",
            IconMoon::AnimalGoat => "\u{1f410}",
            IconMoon::AnimalBactrianCamel => "\u{1f42b}",
            IconMoon::AnimalDromedaryCamel => "\u{1f42a}",
            IconMoon::AnimalCow => "\u{1f404}",
            IconMoon::AnimalHorse => "\u{1f40e}",
            IconMoon::AnimalCat => "\u{1f408}",
            IconMoon::AnimalRabbit => "\u{1f407}",
            IconMoon::AnimalRooster => "\u{1f413}",
            IconMoon::AnimalPig => "\u{1f416}",
            IconMoon::AnimalDolphin => "\u{1f42c}",
            IconMoon::Snake => "\u{1f40d}",
            IconMoon::AnimalSnail => "\u{1f40c}",
            IconMoon::BlackFlorette => "\u{273f}",
            IconMoon::Florette => "\u{2740}",
            IconMoon::Flower => "\u{2698}",
            IconMoon::ChristmasTree => "\u{1f384}",
            IconMoon::TreePine => "\u{1f332}",
            IconMoon::Tree => "\u{1f333}",
            IconMoon::TreePalm => "\u{1f334}",
            IconMoon::Cactus => "\u{1f335}",
            IconMoon::Herb => "\u{1f33f}",
            IconMoon::Leaf => "\u{1f342}",
            IconMoon::MapleLeaf => "\u{1f341}",
            IconMoon::Spider => "\u{1f577}",
            IconMoon::AnimalAnt => "\u{1f41c}",
            IconMoon::Spider7Web => "\u{1f578}",
            IconMoon::PawPrints => "\u{1f43e}",
            IconMoon::Footprints => "\u{1f463}",
            IconMoon::Pedestrian => "\u{1f6b6}",
            IconMoon::Dancing => "\u{1f483}",
            IconMoon::Swimming => "\u{1f3ca}",
            IconMoon::Weighlifting => "\u{1f3cb}",
            IconMoon::IceSkater => "\u{26f8}",
            IconMoon::Skier => "\u{26f7}",
            IconMoon::Snowboarding => "\u{1f3c2}",
            IconMoon::Running => "\u{1f3c3}",
            IconMoon::Bicyclist => "\u{1f6b4}",
            IconMoon::Wheelchair => "\u{267f}",
            IconMoon::Restroom => "\u{1f6bb}",
            IconMoon::WomanAndWoman => "\u{1f46d}",
            IconMoon::ManAndWoman => "\u{1f46b}",
            IconMoon::ManAndMan => "\u{1f46c}",
            IconMoon::Family => "\u{1f46a}",
            IconMoon::Baby => "\u{1f6bc}",
            IconMoon::Eye => "\u{1f441}",
            IconMoon::Ear => "\u{1f442}",
            IconMoon::Hand => "\u{270b}",
            IconMoon::HandFist => "\u{270a}",
            IconMoon::User => "\u{1f464}",
            IconMoon::Users => "\u{1f465}",
            IconMoon::ConstructionWorker => "\u{1f477}",
            IconMoon::PassportControl => "\u{1f6c2}",
            IconMoon::Guard => "\u{1f482}",
            IconMoon::Spy => "\u{1f575}",
            IconMoon::FaceMan => "\u{1f468}",
            IconMoon::FaceWoman => "\u{1f469}",
            IconMoon::FaceBoy => "\u{1f466}",
            IconMoon::FaceGirl => "\u{1f467}",
            IconMoon::FaceBaby => "\u{1f476}",
            IconMoon::FaceCallcenter => "\u{1f481}",
            IconMoon::FacePrincess => "\u{1f478}",
            IconMoon::FaceOldChineseMan => "\u{1f474}",
            IconMoon::FaceManWithTurban => "\u{1f473}",
            IconMoon::FaceSantaClaus => "\u{1f385}",
            IconMoon::Snowman => "\u{2603}",
            IconMoon::Panda => "\u{1f43c}",
            IconMoon::FaceKitty => "\u{1f431}",
            IconMoon::Imp => "\u{1f47f}",
            IconMoon::FaceMonkey => "\u{1f435}",
            IconMoon::FaceBear => "\u{1f43b}",
            IconMoon::FaceHamster => "\u{1f439}",
            IconMoon::FaceChihuahua => "\u{1f436}",
            IconMoon::Alien => "\u{1f47d}",
            IconMoon::Skull => "\u{1f480}",
            IconMoon::Ghost => "\u{1f47b}",
            IconMoon::Comet => "\u{2604}",
            IconMoon::StarEightPoints => "\u{2734}",
            IconMoon::Snowflake => "\u{2744}",
            IconMoon::Rainbow => "\u{1f308}",
            IconMoon::Sun => "\u{2600}",
            IconMoon::Star => "\u{2605}",
            IconMoon::StarOpen => "\u{2606}",
            IconMoon::AceOfDiamonds => "\u{1f0c1}",
            IconMoon::AceOfClubs => "\u{1f0d1}",
            IconMoon::AceOfSpades => "\u{1f0a1}",
            IconMoon::AceOfHearts => "\u{1f0b1}",
            IconMoon::Diamonds => "\u{2666}",
            IconMoon::Clubs => "\u{2663}",
            IconMoon::Spades => "\u{2660}",
            IconMoon::Heart => "\u{2665}",
            IconMoon::HeartBroken => "\u{1f494}",
            IconMoon::HeartBeating => "\u{1f493}",
            IconMoon::HeartRibbon => "\u{1f49d}",
            IconMoon::HeartOpen => "\u{2661}",
            IconMoon::HeartTilted => "\u{2765}",
            IconMoon::Hearts => "\u{1f495}",
            IconMoon::HeartWithArrow => "\u{1f498}",
            IconMoon::Clock => "\u{1f553}",
            IconMoon::Stopwatch => "\u{23f1}",
            IconMoon::Watch => "\u{231a}",
            IconMoon::Target => "\u{1f3af}",
            IconMoon::EnvelopeStamped => "\u{1f583}",
            IconMoon::PhoneLocation => "\u{2706}",
            IconMoon::Graduation => "\u{1f393}",
            IconMoon::Gift => "\u{1f381}",
            IconMoon::Tophat => "\u{1f3a9}",
            IconMoon::Eyeglasses => "\u{1f453}",
            IconMoon::Sunglasses => "\u{1f576}",
            IconMoon::JackOLantern => "\u{1f383}",
            IconMoon::Umbrella => "\u{2602}",
            IconMoon::Headstone => "\u{26fc}",
            IconMoon::Death => "\u{1f571}",
            IconMoon::SkullAndBones => "\u{2620}",
            IconMoon::Coffin => "\u{26b0}",
            IconMoon::Bomb => "\u{1f4a3}",
            IconMoon::Helm => "\u{2388}",
            IconMoon::Crosshairs => "\u{2316}",
            IconMoon::TrafficLight => "\u{1f6a6}",
            IconMoon::Candle => "\u{1f56f}",
            IconMoon::BabyBottle => "\u{1f37c}",
            IconMoon::Pushpin => "\u{1f4cc}",
            IconMoon::Microphone => "\u{1f3a4}",
            IconMoon::Flashlight => "\u{1f526}",
            IconMoon::KeyAlt => "\u{1f5dd}",
            IconMoon::Dagger => "\u{1f5e1}",
            IconMoon::Pistol => "\u{1f52b}",
            IconMoon::Pick => "\u{26cf}",
            IconMoon::Wrench => "\u{1f527}",
            IconMoon::Hammer => "\u{1f528}",
            IconMoon::Ruler2 => "\u{1f4cf}",
            IconMoon::Ruler => "\u{1f4d0}",
            IconMoon::Hourglass => "\u{23f3}",
            IconMoon::Knife => "\u{1f52a}",
            IconMoon::ForkKnife => "\u{1f374}",
            IconMoon::ForkKnifePlate => "\u{1f37d}",
            IconMoon::NutAndBolt => "\u{1f529}",
            IconMoon::Gear => "\u{2699}",
            IconMoon::HammerWrench => "\u{1f6e0}",
            IconMoon::HammerAndPick => "\u{2692}",
            IconMoon::CrossedSwords => "\u{2694}",
            IconMoon::PermanentPaper => "\u{267e}",
            IconMoon::Infinity => "\u{221e}",
            IconMoon::Command => "\u{2318}",
            IconMoon::Retrograde => "\u{211e}",
            IconMoon::Aleph => "\u{2135}",
            IconMoon::Omega => "\u{2126}",
            IconMoon::Registered => "\u{ae}",
            IconMoon::Copyright => "\u{a9}",
            IconMoon::AtSymbol => "\u{ff20}",
            IconMoon::QuestionMark => "\u{ff1f}",
            IconMoon::ExclamationMark => "\u{ff01}",
            IconMoon::BraceLeft => "\u{ff5b}",
            IconMoon::BraceRight => "\u{fe5c}",
            IconMoon::ParenthesisLeft => "\u{ff08}",
            IconMoon::ParenthesisRight => "\u{ff09}",
            IconMoon::SquareBracketLeft => "\u{ff3b}",
            IconMoon::SquareBracketRight => "\u{ff3d}",
            IconMoon::Percent => "\u{ff05}",
            IconMoon::Perthousand => "\u{2030}",
            IconMoon::Ampersand => "\u{ff06}",
            IconMoon::AsteriskFive => "\u{ff0a}",
            IconMoon::Number => "\u{ff03}",
            IconMoon::AsteriskSix => "\u{2731}",
            IconMoon::Scales => "\u{2696}",
            IconMoon::Recycle => "\u{267b}",
            IconMoon::Chessboard => "\u{2593}",
            IconMoon::ChessWhitePawn => "\u{2659}",
            IconMoon::ChessBlackPawn => "\u{265f}",
            IconMoon::ChessWhiteKnight => "\u{2658}",
            IconMoon::ChessBlackKnight => "\u{265e}",
            IconMoon::ChessWhiteBishop => "\u{2657}",
            IconMoon::ChessBlackBishop => "\u{265d}",
            IconMoon::ChessWhiteRook => "\u{2656}",
            IconMoon::ChessBlackRook => "\u{265c}",
            IconMoon::ChessWhiteQueen => "\u{2655}",
            IconMoon::ChessWhiteKing => "\u{2654}",
            IconMoon::ChessBlackKing => "\u{265a}",
            IconMoon::ChessBlackQueen => "\u{265b}",
            IconMoon::CrossPommee => "\u{1f542}",
            IconMoon::Cloud => "\u{2601}",
            IconMoon::CrossOfJerusalem => "\u{2629}",
            IconMoon::MalteseCross => "\u{2720}",
            IconMoon::CrossOrthodox => "\u{2626}",
            IconMoon::ChiRho => "\u{2627}",
            IconMoon::Ankh => "\u{2625}",
            IconMoon::LatinCross => "\u{271d}",
            IconMoon::LatinCrossOutline => "\u{271f}",
            IconMoon::CelticCross => "\u{1f548}",
            IconMoon::CrossOfLorraine => "\u{2628}",
            IconMoon::StarOfDavid => "\u{2721}",
            IconMoon::StarAndCrescent => "\u{262a}",
            IconMoon::Farsi => "\u{262b}",
            IconMoon::Khanda => "\u{262c}",
            IconMoon::Temple => "\u{26e9}",
            IconMoon::Peace => "\u{262e}",
            IconMoon::Shamrock => "\u{2618}",
            IconMoon::FourLeafClover => "\u{1f340}",
            IconMoon::WheelOfDharma => "\u{2638}",
            IconMoon::Om => "\u{1f549}",
            IconMoon::SwastikaRight => "\u{5350}",
            IconMoon::SwastikaLeft => "\u{534d}",
            IconMoon::Pentagram => "\u{26e4}",
            IconMoon::PentagramInverted => "\u{26e7}",
            IconMoon::Radiation => "\u{2622}",
            IconMoon::Biohazard => "\u{2623}",
            IconMoon::Atom => "\u{269b}",
            IconMoon::Caduceus => "\u{2624}",
            IconMoon::Asclepius => "\u{2695}",
            IconMoon::HammerSickle => "\u{262d}",
            IconMoon::Tao => "\u{262f}",
            IconMoon::FleurDeLis => "\u{269c}",
            IconMoon::DigitZero => "\u{ff10}",
            IconMoon::DigitOne => "\u{ff11}",
            IconMoon::DigitTwo => "\u{ff12}",
            IconMoon::DigitThree => "\u{ff13}",
            IconMoon::DigitFour => "\u{ff14}",
            IconMoon::DigitFive => "\u{ff15}",
            IconMoon::DigitSix => "\u{ff16}",
            IconMoon::DigitSeven => "\u{ff17}",
            IconMoon::DigitEight => "\u{ff18}",
            IconMoon::DigitNine => "\u{ff19}",
            IconMoon::Lettera => "\u{ff41}",
            IconMoon::Letterb => "\u{ff42}",
            IconMoon::Letterc => "\u{ff43}",
            IconMoon::Letterd => "\u{ff44}",
            IconMoon::Lettere => "\u{ff45}",
            IconMoon::Letterf => "\u{ff46}",
            IconMoon::Letterg => "\u{ff47}",
            IconMoon::Letterh => "\u{ff48}",
            IconMoon::Letteri => "\u{ff49}",
            IconMoon::Letterj => "\u{ff4a}",
            IconMoon::Letterk => "\u{ff4b}",
            IconMoon::Letterl => "\u{ff4c}",
            IconMoon::Letterm => "\u{ff4d}",
            IconMoon::Lettern => "\u{ff4e}",
            IconMoon::Lettero => "\u{ff4f}",
            IconMoon::Letterp => "\u{ff50}",
            IconMoon::Letterq => "\u{ff51}",
            IconMoon::Letterr => "\u{ff52}",
            IconMoon::Letters => "\u{ff53}",
            IconMoon::Lettert => "\u{ff54}",
            IconMoon::Letteru => "\u{ff55}",
            IconMoon::Letterv => "\u{ff56}",
            IconMoon::Letterw => "\u{ff57}",
            IconMoon::Letterx => "\u{ff58}",
            IconMoon::Lettery => "\u{ff59}",
            IconMoon::Letterz => "\u{ff5a}",
            IconMoon::LetterA => "\u{ff21}",
            IconMoon::LetterB => "\u{ff22}",
            IconMoon::LetterC => "\u{ff23}",
            IconMoon::LetterD => "\u{ff24}",
            IconMoon::LetterE => "\u{ff25}",
            IconMoon::LetterF => "\u{ff26}",
            IconMoon::LetterG => "\u{ff27}",
            IconMoon::LetterH => "\u{ff28}",
            IconMoon::LetterI => "\u{ff29}",
            IconMoon::LetterJ => "\u{ff2a}",
            IconMoon::LetterK => "\u{ff2b}",
            IconMoon::LetterL => "\u{ff2c}",
            IconMoon::LetterM => "\u{ff2d}",
            IconMoon::LetterN => "\u{ff2e}",
            IconMoon::LetterO => "\u{ff2f}",
            IconMoon::LetterP => "\u{ff30}",
            IconMoon::LetterQ => "\u{ff31}",
            IconMoon::LetterR => "\u{ff32}",
            IconMoon::LetterS => "\u{ff34}",
            IconMoon::LetterT => "\u{ff35}",
            IconMoon::LetterU => "\u{ff36}",
            IconMoon::LetterV => "\u{ff37}",
            IconMoon::LetterW => "\u{ff38}",
            IconMoon::LetterX => "\u{ff39}",
            IconMoon::LetterY => "\u{59}",
            IconMoon::LetterZ => "\u{ff3a}",
            IconMoon::WebTwitter => "\u{e603}",
            IconMoon::WebFacebook => "\u{e604}",
            IconMoon::WebTumblr => "\u{e607}",
            IconMoon::WebLinkedin => "\u{e608}",
            IconMoon::WebGoogleplus => "\u{e605}",
            IconMoon::Youtube => "\u{e636}",
            IconMoon::WebStumbleupon => "\u{e60a}",
            IconMoon::WebBehance => "\u{e61a}",
            IconMoon::WebMixi => "\u{e619}",
            IconMoon::WebDelicious => "\u{e629}",
            IconMoon::WebSinaWeibo => "\u{e615}",
            IconMoon::WebPicassa => "\u{e621}",
            IconMoon::WebPicasa => "\u{e617}",
            IconMoon::WebLastfm => "\u{e60b}",
            IconMoon::WebSpotify => "\u{e60d}",
            IconMoon::WebJoomla => "\u{e631}",
            IconMoon::Vk => "\u{f189}",
            IconMoon::WebYelp => "\u{e634}",
            IconMoon::WebVine => "\u{f1ca}",
            IconMoon::WebRdio => "\u{e60c}",
            IconMoon::WebSoundcloud => "\u{e627}",
            IconMoon::Lastfm => "\u{e632}",
            IconMoon::WebFoursquare => "\u{e633}",
            IconMoon::WebVimeo => "\u{e602}",
            IconMoon::WebCircles => "\u{e61b}",
            IconMoon::WebPinterest => "\u{e606}",
            IconMoon::Digg => "\u{f1a6}",
            IconMoon::WebFlattr => "\u{e612}",
            IconMoon::WebInstagram => "\u{e60f}",
            IconMoon::WebRenren => "\u{e614}",
            IconMoon::WebFlickr => "\u{e620}",
            IconMoon::WebDribbble => "\u{e600}",
            IconMoon::WebDeviantart => "\u{e622}",
            IconMoon::WebForrst => "\u{e61e}",
            IconMoon::WebStackoverflow => "\u{e601}",
            IconMoon::WebGithub => "\u{e624}",
            IconMoon::WebGit => "\u{e625}",
            IconMoon::WebReddit => "\u{e628}",
            IconMoon::WebPaypal => "\u{e616}",
            IconMoon::WebSkype => "\u{e613}",
            IconMoon::WebVk => "\u{e61c}",
            IconMoon::WebGoogleDrive => "\u{e62f}",
            IconMoon::WebQq => "\u{e60e}",
            IconMoon::WebDropbox => "\u{e610}",
            IconMoon::WebSteam => "\u{e623}",
            IconMoon::WebEvernote => "\u{e611}",
            IconMoon::WebSmashing => "\u{e61d}",
            IconMoon::WebBlogger => "\u{e626}",
            IconMoon::WebWordpress => "\u{e630}",
            IconMoon::WebDrupal => "\u{e635}",
            IconMoon::BrowserChrome => "\u{e62a}",
            IconMoon::BrowserIe => "\u{e62c}",
            IconMoon::BrowserSafari => "\u{e62e}",
            IconMoon::BrowserFirefox => "\u{e62b}",
            IconMoon::BrowserOpera => "\u{e62d}",
            IconMoon::OsAndroid => "\u{e618}",
            IconMoon::OsWindows => "\u{e61f}",
            IconMoon::OsApple => "\u{f8ff}",
            IconMoon::Linux => "\u{1f427}",
        }
    }
}
