#+STARTUP: logdone
* Notas
+ ~A fecha 240117, instalo sqlx, no para usarla ya, sino porque la he descubierto y me servirá tanto para mysql como para sqlite. Aunque también sirve para postgres, no voy a usarla por ahora con él porque lo tengo más o menos manejado ya. Si a futuro quiero volver a intentar usar tokio con postgres puedo intentarlo usando sqlx y me quito una dependencia, pero no es ni mucho menos algo que me preocupe ahora mismo.~ Ya estoy usando sqlx.
+ Probar a usar =cargo features= para quitar/probar si pasándolo todo funciona, porque quita mucho código (creo).
+ Cada vista tiene su propio estado. Dicho estado se crea y destruye con la propia aplicación obviamente. Pero además, *no se serializa*, no hay forma de pasarlo a un archivo de texto, de importarlo/exportarlo. Todo lo que queramos que pueda ser mantenido entre sesiones ha de ir a las variables de estado de la aplicación: /RedisAppState/, /HttpState/, etc. No tienen consistencia en los nombres, debido a que han ido añadiéndose un poco libremente y ha sido a posterior cuando he visto la conexión entre ellas.
+ Para traerme una carpeta entera de otra rama
#+begin_src git checkout rama -- relative/path
#+end_src

* General
*** TODO Que el menú lateral pueda hacerse más pequeño, incluso ocultando parte de los elementos que tiene dentro.
No sé si es muy factible haciendo desborde de elementos.
*** Crear adaptadores de configuración, y añadir en la configuración un valor que indique la versión que es.
De esta forma podremos a partir de por ejemplo v1 crear un modificador que cree v2, etc. También se puede usar para tener exportadores manuales en los que los usuarios participen en caso de rupturas muy grandes, aunque no debería ser problema. Si alguien pasa de v1 a v8 simplemente tendremos que aplicar de forma secuencial todos los adaptadores.
*OJO* Esto me obliga a tener un versionado del estado, esto es, no puedo chafar el estado sin más, he de guardar las distintas versiones a partir de tener todo eso implementado.
*** Analizar si es interesante usar [[https://github.com/Adanos020/egui_dock][egui_dock]] o [[https://github.com/rerun-io/egui_tiles][egui_tiles]]
*** DONE Manejo de estado mediante función de /fallback/ que rellena uno a uno
CLOSED: [2024-05-25 sáb 12:58]
*** DONE En varias situaciones, dar opción a usuario a invertir el sentido del listado
CLOSED: [2024-02-28 mié 16:22] No está hecho en todo, pero sí en las tablas de Postgres, puedo usar de guía para otras veces que se presente la necesidad.


* Otros
*** Crates a revisar por si fuesen interesante
**** [[https://github.com/tokio-rs/tracing][tracing]]

