// -------------------------------------------------------------------------
// Copyright (C) 2024 Fernando López Laso - All Rights Reserved
//
// Unauthorized copying of this file, via any medium is strictly prohibited.
// This file is confidential and only available to authorized individuals
// with the permission of the copyright holders.
// -------------------------------------------------------------------------

// Casi todo aquí copiado/replicado de sqlx, no exponen PgType y por uvas o peras
// es un follón depender de ese tipo, así que lo que hago es a partir de PgType.name()
// de una columna extraigo este PgType.

// No puedo usar name porque entonces pierdo el enum, puesto cada enum tiene un name
// distinto, y para eso me habría quedado con la implementación con Postgres.

use std::{fmt::Display, sync::Arc};

use sqlx::{
    postgres::{types::Oid, PgTypeInfo, PgTypeKind},
    TypeInfo,
};

#[derive(Debug, Clone)]
#[repr(u32)]
pub enum PgType {
    Bool,
    Bytea,
    Char,
    Name,
    Int8,
    Int2,
    Int4,
    Text,
    Oid,
    Json,
    JsonArray,
    Point,
    Lseg,
    Path,
    Box,
    Polygon,
    Line,
    LineArray,
    Cidr,
    CidrArray,
    Float4,
    Float8,
    Unknown,
    Circle,
    CircleArray,
    Macaddr8,
    Macaddr8Array,
    Macaddr,
    Inet,
    BoolArray,
    ByteaArray,
    CharArray,
    NameArray,
    Int2Array,
    Int4Array,
    TextArray,
    BpcharArray,
    VarcharArray,
    Int8Array,
    PointArray,
    LsegArray,
    PathArray,
    BoxArray,
    Float4Array,
    Float8Array,
    PolygonArray,
    OidArray,
    MacaddrArray,
    InetArray,
    Bpchar,
    Varchar,
    Date,
    Time,
    Timestamp,
    TimestampArray,
    DateArray,
    TimeArray,
    Timestamptz,
    TimestamptzArray,
    Interval,
    IntervalArray,
    NumericArray,
    Timetz,
    TimetzArray,
    Bit,
    BitArray,
    Varbit,
    VarbitArray,
    Numeric,
    Record,
    RecordArray,
    Uuid,
    UuidArray,
    Jsonb,
    JsonbArray,
    Int4Range,
    Int4RangeArray,
    NumRange,
    NumRangeArray,
    TsRange,
    TsRangeArray,
    TstzRange,
    TstzRangeArray,
    DateRange,
    DateRangeArray,
    Int8Range,
    Int8RangeArray,
    Jsonpath,
    JsonpathArray,
    Money,
    MoneyArray,

    // https://www.postgresql.org/docs/9.3/datatype-pseudo.html
    Void,

    // A realized user-defined type. When a connection sees a DeclareXX variant it resolves
    // into this one before passing it along to `accepts` or inside of `Value` objects.
    Custom(Arc<PgCustomType>),
    // From [`PgTypeInfo::with_name`]
    // DeclareWithName(String),

    // NOTE: Do we want to bring back type declaration by ID? It's notoriously fragile but
    //       someone may have a user for it
    // DeclareWithOid(Oid),
}

impl Display for PgType {
    fn fmt(&self, _f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}

// No lo expone la librería.
#[derive(Debug, Clone)]
pub struct PgCustomType {
    pub oid: Oid,
    pub name: String,
    pub kind: PgTypeKind,
}

pub fn ty_to_type(ty: &PgTypeInfo) -> Option<PgType> {
    let oid = ty.oid();
    oid?;

    let kind = ty.kind();
    let name: String = ty.name().to_string();

    Some(match oid.unwrap().0 {
        16 => PgType::Bool,
        17 => PgType::Bytea,
        18 => PgType::Char,
        19 => PgType::Name,
        20 => PgType::Int8,
        21 => PgType::Int2,
        23 => PgType::Int4,
        25 => PgType::Text,
        26 => PgType::Oid,
        114 => PgType::Json,
        199 => PgType::JsonArray,
        600 => PgType::Point,
        601 => PgType::Lseg,
        602 => PgType::Path,
        603 => PgType::Box,
        604 => PgType::Polygon,
        628 => PgType::Line,
        629 => PgType::LineArray,
        650 => PgType::Cidr,
        651 => PgType::CidrArray,
        700 => PgType::Float4,
        701 => PgType::Float8,
        705 => PgType::Unknown,
        718 => PgType::Circle,
        719 => PgType::CircleArray,
        774 => PgType::Macaddr8,
        775 => PgType::Macaddr8Array,
        790 => PgType::Money,
        791 => PgType::MoneyArray,
        829 => PgType::Macaddr,
        869 => PgType::Inet,
        1000 => PgType::BoolArray,
        1001 => PgType::ByteaArray,
        1002 => PgType::CharArray,
        1003 => PgType::NameArray,
        1005 => PgType::Int2Array,
        1007 => PgType::Int4Array,
        1009 => PgType::TextArray,
        1014 => PgType::BpcharArray,
        1015 => PgType::VarcharArray,
        1016 => PgType::Int8Array,
        1017 => PgType::PointArray,
        1018 => PgType::LsegArray,
        1019 => PgType::PathArray,
        1020 => PgType::BoxArray,
        1021 => PgType::Float4Array,
        1022 => PgType::Float8Array,
        1027 => PgType::PolygonArray,
        1028 => PgType::OidArray,
        1040 => PgType::MacaddrArray,
        1041 => PgType::InetArray,
        1042 => PgType::Bpchar,
        1043 => PgType::Varchar,
        1082 => PgType::Date,
        1083 => PgType::Time,
        1114 => PgType::Timestamp,
        1115 => PgType::TimestampArray,
        1182 => PgType::DateArray,
        1183 => PgType::TimeArray,
        1184 => PgType::Timestamptz,
        1185 => PgType::TimestamptzArray,
        1186 => PgType::Interval,
        1187 => PgType::IntervalArray,
        1231 => PgType::NumericArray,
        1266 => PgType::Timetz,
        1270 => PgType::TimetzArray,
        1560 => PgType::Bit,
        1561 => PgType::BitArray,
        1562 => PgType::Varbit,
        1563 => PgType::VarbitArray,
        1700 => PgType::Numeric,
        2278 => PgType::Void,
        2249 => PgType::Record,
        2287 => PgType::RecordArray,
        2950 => PgType::Uuid,
        2951 => PgType::UuidArray,
        3802 => PgType::Jsonb,
        3807 => PgType::JsonbArray,
        3904 => PgType::Int4Range,
        3905 => PgType::Int4RangeArray,
        3906 => PgType::NumRange,
        3907 => PgType::NumRangeArray,
        3908 => PgType::TsRange,
        3909 => PgType::TsRangeArray,
        3910 => PgType::TstzRange,
        3911 => PgType::TstzRangeArray,
        3912 => PgType::DateRange,
        3913 => PgType::DateRangeArray,
        3926 => PgType::Int8Range,
        3927 => PgType::Int8RangeArray,
        4072 => PgType::Jsonpath,
        4073 => PgType::JsonpathArray,
        // Si no es ninguno conocido, doy por hecho que es custom.
        // No es correcto, pero no sé qué hacer sino.
        value => PgType::Custom(Arc::new(PgCustomType {
            oid: Oid(value),
            kind: kind.to_owned(),
            name,
        })),
        // _ => {
        // return None;
        // }
    })
}

impl PgType {
    // pub fn try_to_oid(&self) -> Option<Oid> {
    //     Some(match self {
    //         PgType::Bool => Oid(16),
    //         PgType::Bytea => Oid(17),
    //         PgType::Char => Oid(18),
    //         PgType::Name => Oid(19),
    //         PgType::Int8 => Oid(20),
    //         PgType::Int2 => Oid(21),
    //         PgType::Int4 => Oid(23),
    //         PgType::Text => Oid(25),
    //         PgType::Oid => Oid(26),
    //         PgType::Json => Oid(114),
    //         PgType::JsonArray => Oid(199),
    //         PgType::Point => Oid(600),
    //         PgType::Lseg => Oid(601),
    //         PgType::Path => Oid(602),
    //         PgType::Box => Oid(603),
    //         PgType::Polygon => Oid(604),
    //         PgType::Line => Oid(628),
    //         PgType::LineArray => Oid(629),
    //         PgType::Cidr => Oid(650),
    //         PgType::CidrArray => Oid(651),
    //         PgType::Float4 => Oid(700),
    //         PgType::Float8 => Oid(701),
    //         PgType::Unknown => Oid(705),
    //         PgType::Circle => Oid(718),
    //         PgType::CircleArray => Oid(719),
    //         PgType::Macaddr8 => Oid(774),
    //         PgType::Macaddr8Array => Oid(775),
    //         PgType::Money => Oid(790),
    //         PgType::MoneyArray => Oid(791),
    //         PgType::Macaddr => Oid(829),
    //         PgType::Inet => Oid(869),
    //         PgType::BoolArray => Oid(1000),
    //         PgType::ByteaArray => Oid(1001),
    //         PgType::CharArray => Oid(1002),
    //         PgType::NameArray => Oid(1003),
    //         PgType::Int2Array => Oid(1005),
    //         PgType::Int4Array => Oid(1007),
    //         PgType::TextArray => Oid(1009),
    //         PgType::BpcharArray => Oid(1014),
    //         PgType::VarcharArray => Oid(1015),
    //         PgType::Int8Array => Oid(1016),
    //         PgType::PointArray => Oid(1017),
    //         PgType::LsegArray => Oid(1018),
    //         PgType::PathArray => Oid(1019),
    //         PgType::BoxArray => Oid(1020),
    //         PgType::Float4Array => Oid(1021),
    //         PgType::Float8Array => Oid(1022),
    //         PgType::PolygonArray => Oid(1027),
    //         PgType::OidArray => Oid(1028),
    //         PgType::MacaddrArray => Oid(1040),
    //         PgType::InetArray => Oid(1041),
    //         PgType::Bpchar => Oid(1042),
    //         PgType::Varchar => Oid(1043),
    //         PgType::Date => Oid(1082),
    //         PgType::Time => Oid(1083),
    //         PgType::Timestamp => Oid(1114),
    //         PgType::TimestampArray => Oid(1115),
    //         PgType::DateArray => Oid(1182),
    //         PgType::TimeArray => Oid(1183),
    //         PgType::Timestamptz => Oid(1184),
    //         PgType::TimestamptzArray => Oid(1185),
    //         PgType::Interval => Oid(1186),
    //         PgType::IntervalArray => Oid(1187),
    //         PgType::NumericArray => Oid(1231),
    //         PgType::Timetz => Oid(1266),
    //         PgType::TimetzArray => Oid(1270),
    //         PgType::Bit => Oid(1560),
    //         PgType::BitArray => Oid(1561),
    //         PgType::Varbit => Oid(1562),
    //         PgType::VarbitArray => Oid(1563),
    //         PgType::Numeric => Oid(1700),
    //         PgType::Void => Oid(2278),
    //         PgType::Record => Oid(2249),
    //         PgType::RecordArray => Oid(2287),
    //         PgType::Uuid => Oid(2950),
    //         PgType::UuidArray => Oid(2951),
    //         PgType::Jsonb => Oid(3802),
    //         PgType::JsonbArray => Oid(3807),
    //         PgType::Int4Range => Oid(3904),
    //         PgType::Int4RangeArray => Oid(3905),
    //         PgType::NumRange => Oid(3906),
    //         PgType::NumRangeArray => Oid(3907),
    //         PgType::TsRange => Oid(3908),
    //         PgType::TsRangeArray => Oid(3909),
    //         PgType::TstzRange => Oid(3910),
    //         PgType::TstzRangeArray => Oid(3911),
    //         PgType::DateRange => Oid(3912),
    //         PgType::DateRangeArray => Oid(3913),
    //         PgType::Int8Range => Oid(3926),
    //         PgType::Int8RangeArray => Oid(3927),
    //         PgType::Jsonpath => Oid(4072),
    //         PgType::JsonpathArray => Oid(4073),
    //         PgType::Custom(ty) => ty.oid,
    //         PgType::DeclareWithOid(oid) => *oid,
    //         PgType::DeclareWithName(_) => {
    //             return None;
    //         }
    //     })
    // }

    // pub fn to_str(&self) -> &str {
    //     match self {
    //         PgType::Bool => "BOOL",
    //         PgType::Bytea => "BYTEA",
    //         PgType::Char => "\"CHAR\"",
    //         PgType::Name => "NAME",
    //         PgType::Int8 => "INT8",
    //         PgType::Int2 => "INT2",
    //         PgType::Int4 => "INT4",
    //         PgType::Text => "TEXT",
    //         PgType::Oid => "OID",
    //         PgType::Json => "JSON",
    //         PgType::JsonArray => "JSON[]",
    //         PgType::Point => "POINT",
    //         PgType::Lseg => "LSEG",
    //         PgType::Path => "PATH",
    //         PgType::Box => "BOX",
    //         PgType::Polygon => "POLYGON",
    //         PgType::Line => "LINE",
    //         PgType::LineArray => "LINE[]",
    //         PgType::Cidr => "CIDR",
    //         PgType::CidrArray => "CIDR[]",
    //         PgType::Float4 => "FLOAT4",
    //         PgType::Float8 => "FLOAT8",
    //         PgType::Unknown => "UNKNOWN",
    //         PgType::Circle => "CIRCLE",
    //         PgType::CircleArray => "CIRCLE[]",
    //         PgType::Macaddr8 => "MACADDR8",
    //         PgType::Macaddr8Array => "MACADDR8[]",
    //         PgType::Macaddr => "MACADDR",
    //         PgType::Inet => "INET",
    //         PgType::BoolArray => "BOOL[]",
    //         PgType::ByteaArray => "BYTEA[]",
    //         PgType::CharArray => "\"CHAR\"[]",
    //         PgType::NameArray => "NAME[]",
    //         PgType::Int2Array => "INT2[]",
    //         PgType::Int4Array => "INT4[]",
    //         PgType::TextArray => "TEXT[]",
    //         PgType::BpcharArray => "CHAR[]",
    //         PgType::VarcharArray => "VARCHAR[]",
    //         PgType::Int8Array => "INT8[]",
    //         PgType::PointArray => "POINT[]",
    //         PgType::LsegArray => "LSEG[]",
    //         PgType::PathArray => "PATH[]",
    //         PgType::BoxArray => "BOX[]",
    //         PgType::Float4Array => "FLOAT4[]",
    //         PgType::Float8Array => "FLOAT8[]",
    //         PgType::PolygonArray => "POLYGON[]",
    //         PgType::OidArray => "OID[]",
    //         PgType::MacaddrArray => "MACADDR[]",
    //         PgType::InetArray => "INET[]",
    //         PgType::Bpchar => "CHAR",
    //         PgType::Varchar => "VARCHAR",
    //         PgType::Date => "DATE",
    //         PgType::Time => "TIME",
    //         PgType::Timestamp => "TIMESTAMP",
    //         PgType::TimestampArray => "TIMESTAMP[]",
    //         PgType::DateArray => "DATE[]",
    //         PgType::TimeArray => "TIME[]",
    //         PgType::Timestamptz => "TIMESTAMPTZ",
    //         PgType::TimestamptzArray => "TIMESTAMPTZ[]",
    //         PgType::Interval => "INTERVAL",
    //         PgType::IntervalArray => "INTERVAL[]",
    //         PgType::NumericArray => "NUMERIC[]",
    //         PgType::Timetz => "TIMETZ",
    //         PgType::TimetzArray => "TIMETZ[]",
    //         PgType::Bit => "BIT",
    //         PgType::BitArray => "BIT[]",
    //         PgType::Varbit => "VARBIT",
    //         PgType::VarbitArray => "VARBIT[]",
    //         PgType::Numeric => "NUMERIC",
    //         PgType::Record => "RECORD",
    //         PgType::RecordArray => "RECORD[]",
    //         PgType::Uuid => "UUID",
    //         PgType::UuidArray => "UUID[]",
    //         PgType::Jsonb => "JSONB",
    //         PgType::JsonbArray => "JSONB[]",
    //         PgType::Int4Range => "INT4RANGE",
    //         PgType::Int4RangeArray => "INT4RANGE[]",
    //         PgType::NumRange => "NUMRANGE",
    //         PgType::NumRangeArray => "NUMRANGE[]",
    //         PgType::TsRange => "TSRANGE",
    //         PgType::TsRangeArray => "TSRANGE[]",
    //         PgType::TstzRange => "TSTZRANGE",
    //         PgType::TstzRangeArray => "TSTZRANGE[]",
    //         PgType::DateRange => "DATERANGE",
    //         PgType::DateRangeArray => "DATERANGE[]",
    //         PgType::Int8Range => "INT8RANGE",
    //         PgType::Int8RangeArray => "INT8RANGE[]",
    //         PgType::Jsonpath => "JSONPATH",
    //         PgType::JsonpathArray => "JSONPATH[]",
    //         PgType::Money => "MONEY",
    //         PgType::MoneyArray => "MONEY[]",
    //         PgType::Void => "VOID",
    //         PgType::Custom(ty) => &*ty.name,
    //         PgType::DeclareWithOid(_) => "?",
    //         PgType::DeclareWithName(name) => name,
    //     }
    // }

    // pub fn to_string(&self) -> String {
    // self.to_str().to_string()
    // }

    pub fn from_string(s: &str) -> Self {
        match s.to_ascii_uppercase().as_str() {
            "BOOL" => PgType::Bool,
            "BYTEA" => PgType::Bytea,
            "\"CHAR\"" => PgType::Char,
            "NAME" => PgType::Name,
            "INT8" => PgType::Int8,
            "INT2" => PgType::Int2,
            "INT4" => PgType::Int4,
            "TEXT" => PgType::Text,
            "OID" => PgType::Oid,
            "JSON" => PgType::Json,
            "_JSON" => PgType::JsonArray,
            "POINT" => PgType::Point,
            "LSEG" => PgType::Lseg,
            "PATH" => PgType::Path,
            "BOX" => PgType::Box,
            "POLYGON" => PgType::Polygon,
            "LINE" => PgType::Line,
            "_LINE" => PgType::LineArray,
            "CIDR" => PgType::Cidr,
            "_CIDR" => PgType::CidrArray,
            "FLOAT4" => PgType::Float4,
            "FLOAT8" => PgType::Float8,
            "UNKNOWN" => PgType::Unknown,
            "CIRCLE" => PgType::Circle,
            "_CIRCLE" => PgType::CircleArray,
            "MACADDR8" => PgType::Macaddr8,
            "_MACADDR8" => PgType::Macaddr8Array,
            "MACADDR" => PgType::Macaddr,
            "INET" => PgType::Inet,
            "_BOOL" => PgType::BoolArray,
            "_BYTEA" => PgType::ByteaArray,
            "\"_CHAR\"" => PgType::CharArray,
            "_NAME" => PgType::NameArray,
            "_INT2" => PgType::Int2Array,
            "_INT4" => PgType::Int4Array,
            "_TEXT" => PgType::TextArray,
            "_CHAR" => PgType::BpcharArray,
            "_VARCHAR" => PgType::VarcharArray,
            "_INT8" => PgType::Int8Array,
            "_POINT" => PgType::PointArray,
            "_LSEG" => PgType::LsegArray,
            "_PATH" => PgType::PathArray,
            "_BOX" => PgType::BoxArray,
            "_FLOAT4" => PgType::Float4Array,
            "_FLOAT8" => PgType::Float8Array,
            "_POLYGON" => PgType::PolygonArray,
            "_OID" => PgType::OidArray,
            "_MACADDR" => PgType::MacaddrArray,
            "_INET" => PgType::InetArray,
            "CHAR" => PgType::Bpchar,
            "VARCHAR" => PgType::Varchar,
            "DATE" => PgType::Date,
            "TIME" => PgType::Time,
            "TIMESTAMP" => PgType::Timestamp,
            "_TIMESTAMP" => PgType::TimestampArray,
            "_DATE" => PgType::DateArray,
            "_TIME" => PgType::TimeArray,
            "TIMESTAMPTZ" => PgType::Timestamptz,
            "_TIMESTAMPTZ" => PgType::TimestamptzArray,
            "INTERVAL" => PgType::Interval,
            "_INTERVAL" => PgType::IntervalArray,
            "_NUMERIC" => PgType::NumericArray,
            "TIMETZ" => PgType::Timetz,
            "_TIMETZ" => PgType::TimetzArray,
            "BIT" => PgType::Bit,
            "_BIT" => PgType::BitArray,
            "VARBIT" => PgType::Varbit,
            "_VARBIT" => PgType::VarbitArray,
            "NUMERIC" => PgType::Numeric,
            "RECORD" => PgType::Record,
            "_RECORD" => PgType::RecordArray,
            "UUID" => PgType::Uuid,
            "_UUID" => PgType::UuidArray,
            "JSONB" => PgType::Jsonb,
            "_JSONB" => PgType::JsonbArray,
            "INT4RANGE" => PgType::Int4Range,
            "_INT4RANGE" => PgType::Int4RangeArray,
            "NUMRANGE" => PgType::NumRange,
            "_NUMRANGE" => PgType::NumRangeArray,
            "TSRANGE" => PgType::TsRange,
            "_TSRANGE" => PgType::TsRangeArray,
            "TSTZRANGE" => PgType::TstzRange,
            "_TSTZRANGE" => PgType::TstzRangeArray,
            "DATERANGE" => PgType::DateRange,
            "_DATERANGE" => PgType::DateRangeArray,
            "INT8RANGE" => PgType::Int8Range,
            "_INT8RANGE" => PgType::Int8RangeArray,
            "JSONPATH" => PgType::Jsonpath,
            "_JSONPATH" => PgType::JsonpathArray,
            "MONEY" => PgType::Money,
            "_MONEY" => PgType::MoneyArray,
            "VOID" => PgType::Void,
            _ => todo!(),
        }
    }
}
