// -------------------------------------------------------------------------
// Copyright (C) 2023 Fernando López Laso - All Rights Reserved
//
// Unauthorized copying of this file, via any medium is strictly prohibited.
// This file is confidential and only available to authorized individuals
// with the permission of the copyright holders.
// -------------------------------------------------------------------------

use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, PartialEq, Eq, Serialize, Deserialize, Debug, Default)]
pub enum I18nOptions {
    #[default]
    ES,
    EN,
}

#[derive(Clone)]
pub struct I18n {
    // intern: I18nOptions,
    pub debug_json_string: String,

    // Barra superior
    pub top_menu_config: String,
    pub top_http_toggle_sidebar: String,
    pub top_redis_toggle_sidebar: String,
    pub top_pg_toggle_sidebar_connections: String,
    pub top_pg_toggle_sidebar_tables: String,
    pub top_kafka_toggle_sidebar_cluster: String,
    pub top_mongo_toggle_sidebar_connections: String,
    pub top_sqlite_toggle_sidebar_connections: String,
    pub top_mysql_toggle_sidebar_connections: String,
    pub top_import_json_state: String,
    pub top_export_json_state: String,
    pub top_export_warning: String,

    // Http
    pub http_btn_edit_ws_name: String,
    pub http_btn_delete_ws: String,
    pub http_btn_update_request: String,
    pub http_btn_send_request: String,
    pub http_send_to_http_performance: String,

    // Kafka
    pub kafka_btn_add_connection: String,
    pub kafka_edit_cluster_name_label: String,
    pub kafka_edit_cluster_host_label: String,
    pub kafka_edit_cluster_port_label: String,
    pub kafka_edit_cluster_save: String,
    pub kafka_edit_cluster_cancel: String,
    pub kafka_btn_connect: String,
    pub kafka_btn_disconnect: String,
    pub kafka_btn_show_brokers: String,
    pub kafka_btn_show_subscription: String,
    pub kafka_btn_show_topics: String,

    // Mongo
    pub mongo_connection_host: String,
    pub mongo_connection_port: String,
    pub mongo_connection_user: String,
    pub mongo_connection_password: String,
    pub mongo_connection_srv: String,
    pub mongo_actions: String,
    pub mongo_insert_one_error: String,
    pub mongo_invalid_doc_to_insert: String,
    pub mongo_clean_filter: String,
    pub mongo_clean_parent: String,
    pub mongo_previsualize_filter: String,
    pub mongo_connections: String,
    pub mongo_databases: String,
    pub mongo_collections: String,
    pub mongo_close_connection: String,
    pub mongo_delete_connection: String,
    pub mongo_copy_database_info: String,
    pub mongo_copy_collection_info: String,
    pub mongo_error_client_uninitialized: String,
    pub mongo_delete_filter: String,
    pub mongo_wrong_action: String,
    pub mongo_filter_heading: String,
    pub mongo_new_document_heading: String,
    pub mongo_doc_menu_copy: String,
    pub mongo_doc_menu_delete_by_id: String,

    // Redis
    pub redis_connections: String,
    pub redis_data_structures: String,
    pub redis_connection_host: String,
    pub redis_connection_port: String,
    pub redis_edit_connection_cancel: String,
    pub redis_edit_connection_save: String,
    pub redis_close_connection: String,
    pub redis_delete_connection: String,
    pub redis_channel: String,
    pub redis_channel_value: String,
    pub redis_channel_publish: String,
    pub redis_close_channel: String,
    pub redis_delete_channel: String,
    pub redis_channel_subscribe: String,
    pub redis_n_columns: String,
    pub redis_clean_messages: String,
    pub redis_close_subscription: String,
    pub redis_delete_subscription: String,
    pub redis_send_command: String,
    pub redis_delete_ds: String,
    pub redis_load: String,
    pub redis_stream_hover_info: String,

    // Postgres
    pub pg_connection_host: String,
    pub pg_connection_port: String,
    pub pg_connection_user: String,
    pub pg_connection_password: String,
    pub pg_connection_dbname: String,
    pub pg_btn_add_connection: String,
    pub pg_btn_connect: String,
    pub pg_btn_connected: String,
    pub pg_btn_load_tables: String,
    pub pg_btn_clean_table: String,
    pub pg_header_connection: String,
    pub pg_btn_query: String,
    pub pg_btn_table_data_generator: String,
    pub pg_btn_table_data_insertion: String,
    pub pg_impossible_to_connect: String,
    pub pg_connection: String,
    pub pg_no_connection: String,
    pub pg_info_performance_table: String,
    pub pg_performance_table: String,

    // Mysql
    pub mysql_info_performance_table: String,
    pub mysql_performance_table: String,

    // Sqlite
    pub sqlite_btn_add_connection: String,
    pub sqlite_btn_table_data_generator: String,
    pub sqlite_btn_clean_table: String,
    pub sqlite_btn_table_data_insertion: String,
    pub sqlite_info_performance_table: String,
    pub sqlite_performance_table: String,
}

pub fn language_selector(i: I18nOptions) -> I18n {
    match i {
        I18nOptions::ES => I18n {
            // intern: I18nOptions::ES,
            debug_json_string: "JSON Exportado".to_owned(),

            // Barra superior
            top_menu_config: "Configuración".to_owned(),
            top_http_toggle_sidebar: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_redis_toggle_sidebar: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_pg_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_pg_toggle_sidebar_tables: "Colapsar/Mostrar Tablas".to_owned(),
            top_kafka_toggle_sidebar_cluster: "Colapsar/Mostar Clústers".to_owned(),
            top_mongo_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_sqlite_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_mysql_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_import_json_state: "Importar estado desde JSON".to_owned(),
            top_export_json_state: "Exportar a JSON".to_owned(),
            top_export_warning: "Exportar sobreescribirá los datos que tenga guardados actualmente".to_owned(),

            // Http
            http_btn_edit_ws_name: "Editar nombre del espacio de trabajo".to_owned(),
            http_btn_delete_ws: "Borrar espacio de trabajo".to_owned(),
            http_btn_update_request: "Actualizar".to_owned(),
            http_btn_send_request: "Lanzar Petición".to_owned(),
            http_send_to_http_performance: "Rendimiento de la Petición".to_owned(),

            // Kafka
            kafka_btn_add_connection: "Añadir Clúster".to_owned(),
            kafka_edit_cluster_name_label: "Nombre del Clúster".to_owned(),
            kafka_edit_cluster_host_label: "Host".to_owned(),
            kafka_edit_cluster_port_label: "Puerto".to_owned(),
            kafka_edit_cluster_save: "Guardar".to_owned(),
            kafka_edit_cluster_cancel: "Cancelar".to_owned(),
            kafka_btn_connect: "Conectar".to_owned(),
            kafka_btn_disconnect: "Desconectar".to_owned(),
            kafka_btn_show_brokers: "Brokers".to_owned(),
            kafka_btn_show_subscription: "Subscripción".to_owned(),
            kafka_btn_show_topics: "Topics".to_owned(),

            // Mongo
            mongo_connection_host: "Host".to_owned(),
            mongo_connection_port: "Puerto".to_owned(),
            mongo_connection_user: "Usuario".to_owned(),
            mongo_connection_password: "Password".to_owned(),
            mongo_connection_srv: "SRV".to_owned(),
            mongo_actions: "Seleccionar Acción".to_owned(),
            mongo_insert_one_error: String::from("InsertOne acepta un único elemento"),
            mongo_invalid_doc_to_insert: String::from("El Documento que se está intentando isnertar no es válido"),
            mongo_clean_filter: String::from("Limpiar Filtro"),
            mongo_clean_parent: String::from("Borrar Padre Actual"),
            mongo_previsualize_filter: String::from("Previsualizar Filtro"),
            mongo_connections: String::from("Conexiones"),
            mongo_databases: String::from("Bases de Datos"),
            mongo_collections: String::from("Colecciones"),
            mongo_close_connection: String::from("Cerrar Conexión"),
            mongo_delete_connection: String::from("Borrar Conexión"),
            mongo_copy_database_info: String::from("Copiar Información de la Base de Datos"),
            mongo_copy_collection_info: String::from("Copiar Información de la Colección"),
            mongo_error_client_uninitialized: String::from("Cliente no Inicializado"),
            mongo_delete_filter: String::from("Borrar Filtro"),
            mongo_wrong_action: String::from("Acción Incorrecta"),
            mongo_filter_heading: String::from("Filtro"),
            mongo_new_document_heading: String::from("Nuevo Documento"),
            mongo_doc_menu_copy: String::from("Copiar Documento"),
            mongo_doc_menu_delete_by_id: String::from("Borrar usando _id"),

            // Redis
            redis_connections: String::from("Conexiones"),
            redis_connection_host: String::from("Host"),
            redis_connection_port: String::from("Puerto"),
            redis_data_structures: String::from("Estructuras de Datos"),
            redis_edit_connection_cancel: String::from("Cancelar"),
            redis_edit_connection_save: String::from("Guardar"),
            redis_close_connection: String::from("Editar Conexión"),
            redis_delete_connection: String::from("Borrar Conexión"),
            redis_channel: String::from("Canal"),
            redis_close_channel: String::from("Cerrar Canal"),
            redis_delete_channel: String::from("Borrar Canal"),
            redis_channel_value: String::from("Valor"),
            redis_channel_publish: String::from("Publicar"),
            redis_channel_subscribe: String::from("Subscribir"),
            redis_n_columns: String::from("Número de Columnas"),
            redis_clean_messages: String::from("Limpiar Mensajes"),
            redis_close_subscription: String::from("Cerrar Subscripción"),
            redis_delete_subscription: String::from("Borrar Subscripción"),
            redis_send_command: String::from("Ejecutar"),
            redis_delete_ds: String::from("Borrar"),
            redis_load: String::from("Cargar"),
            redis_stream_hover_info: String::from("Clicka para abrir el Stream y reenviarlo"),
            
            // Postgres
            pg_connection_host: "Host".to_owned(),
            pg_connection_port: "Puerto".to_owned(),
            pg_connection_user: "Usuario".to_owned(),
            pg_connection_password: "Contraseña".to_owned(),
            pg_connection_dbname: "Base de Datos".to_owned(),
            pg_btn_add_connection: "Anadir Conexión".to_owned(),
            pg_btn_connect: "Conectar".to_owned(),
            pg_btn_connected: "Conectado".to_owned(),
            pg_btn_load_tables: "Cargar Tablas".to_owned(),
            pg_btn_clean_table: "Limpiar Tabla".to_owned(),
            pg_btn_query: "Ejecutar".to_owned(),
            pg_btn_table_data_generator: "Generación de Datos".to_owned(),
            pg_btn_table_data_insertion: "Insertar Fila".to_owned(),
            pg_header_connection: "Conexión".to_owned(),
            pg_impossible_to_connect: "Imposible conectar con Postgres.".to_owned(),
            pg_connection: "Conectado.".to_owned(),
            pg_no_connection: "No conectado.".to_owned(),
            pg_info_performance_table: "El borrado de filas no es posible con tabla con mejor rendimiento.\nSeleccione esta opción para una cantidad de celdas (celdas x columnas) masiva, del orden de 1e5, o cuando la cantidad de datos dentro de las celdas pueda ser muy grande y tenga centeneras o miles de estas celdas, como puede ser el caso de grandes textos, json, binarios, arrays o datos geográficos.".to_owned(),
            pg_performance_table: "Tabla Optimizada".to_owned(),

            // Mysql
            mysql_info_performance_table: "El borrado de filas no es posible con tabla con mejor rendimiento.\nSeleccione esta opción para una cantidad de celdas (celdas x columnas) masiva, del orden de 1e5, o cuando la cantidad de datos dentro de las celdas pueda ser muy grande y tenga centeneras o miles de estas celdas, como puede ser el caso de grandes textos, json, binarios o datos geográficos.".to_owned(),
            mysql_performance_table: "Tabla Optimizada".to_owned(),

            // Sqlite
            sqlite_btn_add_connection: "Abrir Archivo".to_owned(),
            sqlite_btn_table_data_generator: "Generación de Datos".to_owned(),
            sqlite_btn_clean_table: "Limpiar Tabla".to_owned(),
            sqlite_btn_table_data_insertion: "Insertar Fila".to_owned(),
            sqlite_info_performance_table: "El borrado de filas no es posible con tabla con mejor rendimiento.\nSeleccione esta opción para una cantidad de celdas (celdas x columnas) masiva, del orden de 1e5, o cuando la cantidad de datos dentro de las celdas pueda ser muy grande y tenga centeneras o miles de estas celdas, como puede ser el caso de grandes textos, binarios o datos geográficos.".to_owned(),
            sqlite_performance_table: "Tabla Optimizada".to_owned(),
        },

        I18nOptions::EN => I18n {
            // intern: I18nOptions::EN,
            debug_json_string: "Exported JSON".to_owned(),

            // Barra superior
            top_menu_config: "Config".to_owned(),
            top_http_toggle_sidebar: "Collapse/Show Sidebar".to_owned(),
            top_redis_toggle_sidebar: "Collapse/Show Sidebar".to_owned(),
            top_pg_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_pg_toggle_sidebar_tables: "Collapse/Show Tables".to_owned(),
            top_kafka_toggle_sidebar_cluster: "Collapse/Show Clusters".to_owned(),
            top_mongo_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_sqlite_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_mysql_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_import_json_state: "Import state from JSON".to_owned(),
            top_export_json_state: "Export to JSON".to_owned(),
            top_export_warning: "Export will override data currently stored".to_owned(),

            // Http
            http_btn_edit_ws_name: "Edit workspace name".to_owned(),
            http_btn_delete_ws: "Delete workspace".to_owned(),
            http_btn_update_request: "Update".to_owned(),
            http_btn_send_request: "Send Request".to_owned(),
            http_send_to_http_performance: "Request Performance".to_owned(),

            // Kafka
            kafka_btn_add_connection: "Add Cluster".to_owned(),
            kafka_edit_cluster_name_label: "Cluster Name".to_owned(),
            kafka_edit_cluster_host_label: "Host".to_owned(),
            kafka_edit_cluster_port_label: "Port".to_owned(),
            kafka_edit_cluster_save: "Save".to_owned(),
            kafka_edit_cluster_cancel: "Cancel".to_owned(),
            kafka_btn_connect: "Connect".to_owned(),
            kafka_btn_disconnect: "Disconnect".to_owned(),
            kafka_btn_show_brokers: "Brokers".to_owned(),
            kafka_btn_show_subscription: "Subscription".to_owned(),
            kafka_btn_show_topics: "Topics".to_owned(),

            // Mongo
            mongo_connection_host: "Host".to_owned(),
            mongo_connection_port: "Port".to_owned(),
            mongo_connection_user: "User".to_owned(),
            mongo_connection_password: "Password".to_owned(),
            mongo_connection_srv: "SRV".to_owned(),
            mongo_actions: "Select Action".to_owned(),
            mongo_insert_one_error: String::from("InsertOne only accepts one element"),
            mongo_invalid_doc_to_insert: String::from("Invalid document"),
            mongo_clean_filter: String::from("Clean Filter"),
            mongo_clean_parent: String::from("Delete Current Parent"),
            mongo_previsualize_filter: String::from("Filter Previsualization"),
            mongo_connections: String::from("Connections"),
            mongo_databases: String::from("Databases"),
            mongo_collections: String::from("Colecciones"),
            mongo_close_connection: String::from("Close Connection"),
            mongo_delete_connection: String::from("Delete Connection"),
            mongo_copy_database_info: String::from("Copy Database Info"),
            mongo_copy_collection_info: String::from("Copy Collection Info"),
            mongo_error_client_uninitialized: String::from("Client does not Exists"),
            mongo_delete_filter: String::from("Delete Filter"),
            mongo_wrong_action: String::from("Wrong Action"),
            mongo_filter_heading: String::from("Filter"),
            mongo_new_document_heading: String::from("New Document"),
            mongo_doc_menu_copy: String::from("Copy Document"),
            mongo_doc_menu_delete_by_id: String::from("Delete using _id"),

            // Redis
            redis_connections: String::from("Connections"),
            redis_data_structures: String::from("Data Structures"),
            redis_edit_connection_cancel: String::from("Cancel"),
            redis_edit_connection_save: String::from("Save"),
            redis_connection_host: String::from("Host"),
            redis_connection_port: String::from("Port"),
            redis_close_connection: String::from("Edit Connection"),
            redis_delete_connection: String::from("Delete Connection"),
            redis_channel: String::from("Channel"),
            redis_close_channel: String::from("Close Channel"),
            redis_delete_channel: String::from("Delete Channel"),
            redis_channel_value: String::from("Value"),
            redis_channel_publish: String::from("Publish"),
            redis_channel_subscribe: String::from("Subscribe"),
            redis_n_columns: String::from("Number of Columns"),
            redis_clean_messages: String::from("Clear Messages"),
            redis_close_subscription: String::from("Close Subscription"),
            redis_delete_subscription: String::from("Delete Subscription"),
            redis_send_command: String::from("Send Command"),
            redis_delete_ds: String::from("Delete"),
            redis_load: String::from("Load"),
redis_stream_hover_info: String::from("Click to Open Stream and enabling resend"),

            // Postgres
            pg_info_performance_table: "Deletion is forbidden for performance table.\nSelect this for massive quantity of cells (rows x columns), order of 1e5, or when massive amount of data inside the cells, like long varchar, big json/binaries/arrays or geographical data.".to_owned(),
            pg_connection_host: "Host".to_owned(),
            pg_connection_port: "Port".to_owned(),
            pg_connection_user: "User".to_owned(),
            pg_connection_password: "Password".to_owned(),
            pg_connection_dbname: "Database".to_owned(),
            pg_btn_add_connection: "Add Connection".to_owned(),
            pg_btn_connect: "Connect".to_owned(),
            pg_btn_connected: "Connectec".to_owned(),
            pg_btn_load_tables: "Load Tables".to_owned(),
            pg_btn_clean_table: "Clean Table".to_owned(),
            pg_btn_query: "Run".to_owned(),
            pg_btn_table_data_generator: "Data Generation".to_owned(),
            pg_btn_table_data_insertion: "Insert Row".to_owned(),
            pg_header_connection: "Connection".to_owned(),
            pg_impossible_to_connect: "Impossible to connect with Postgres.".to_owned(),
            pg_connection: "Connected.".to_owned(),
            pg_no_connection: "No connected.".to_owned(),
            pg_performance_table: "Performance Table".to_owned(),

            // Mysql
            mysql_info_performance_table: "Deletion is forbidden for performance table.\nSelect this for massive quantity of cells (rows x columns), order of 1e5, or when massive amount of data inside the cells, like long texts, big binaries/jsons, or geographical data.".to_owned(),
            mysql_performance_table: "Performance Table".to_owned(),

            // Sqlite
            sqlite_btn_add_connection: "Open File".to_owned(),
            sqlite_btn_table_data_generator: "Data Generation".to_owned(),
            sqlite_btn_clean_table: "Clean Table".to_owned(),
            sqlite_btn_table_data_insertion: "Insert Row".to_owned(),
            sqlite_info_performance_table: "Deletion is forbidden for performance table.\nSelect this for massive quantity of cells (rows x columns), order of 1e5, or when massive amount of data inside the cells, like long varchar, big binaries o geographical data.".to_owned(),
            sqlite_performance_table: "Performance Table".to_owned(),
        },
    }
}
