// -------------------------------------------------------------------------
// Copyright (C) 2023 Fernando López Laso - All Rights Reserved
//
// Unauthorized copying of this file, via any medium is strictly prohibited.
// This file is confidential and only available to authorized individuals
// with the permission of the copyright holders.
// -------------------------------------------------------------------------

use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum I18nOptions {
    ES,
    EN,
}

impl Default for I18nOptions {
    fn default() -> Self {
        I18nOptions::ES
    }
}

#[derive(Clone)]
pub struct I18n {
    // intern: I18nOptions,
    pub debug_json_string: String,
    pub top_menu_config: String,
    pub top_http_toggle_sidebar: String,
    pub top_redis_toggle_sidebar: String,
    pub top_pg_toggle_sidebar_connections: String,
    pub top_pg_toggle_sidebar_tables: String,
    pub top_kafka_toggle_sidebar_cluster: String,
    pub top_mongo_toggle_sidebar_connections: String,
    pub top_sqlite_toggle_sidebar_connections: String,
    pub top_mysql_toggle_sidebar_connections: String,
    pub http_btn_edit_ws_name: String,
    pub http_btn_delete_ws: String,
    pub http_btn_update_request: String,
    pub http_btn_send_request: String,
    pub http_send_to_http_performance: String,
    pub pg_connection_host: String,
    pub pg_connection_port: String,
    pub pg_connection_user: String,
    pub pg_connection_password: String,
    pub pg_connection_dbname: String,
    pub pg_btn_add_connection: String,
    pub pg_btn_connect: String,
    pub pg_btn_connected: String,
    pub pg_btn_load_tables: String,
    pub pg_btn_clean_table: String,
    pub pg_header_connection: String,
    pub pg_btn_query: String,
    pub pg_btn_table_data_generator: String,
    pub pg_btn_table_data_insertion: String,
    pub pg_impossible_to_connect: String,
    pub pg_connection: String,
    pub pg_no_connection: String,
    pub kafka_btn_add_connection: String,
    pub kafka_edit_cluster_name_label: String,
    pub kafka_edit_cluster_host_label: String,
    pub kafka_edit_cluster_port_label: String,
    pub kafka_edit_cluster_save: String,
    pub kafka_edit_cluster_cancel: String,
    pub kafka_btn_connect: String,
    pub kafka_btn_disconnect: String,
    pub kafka_btn_show_brokers: String,
    pub kafka_btn_show_subscription: String,
    pub kafka_btn_show_topics: String,
    pub sqlite_btn_add_connection: String,
    pub sqlite_btn_table_data_generator: String,
    pub sqlite_btn_clean_table: String,
    pub sqlite_btn_table_data_insertion: String,
    pub mongo_connection_host: String,
    pub mongo_connection_port: String,
    pub mongo_connection_user: String,
    pub mongo_connection_password: String,
    pub mongo_connection_srv: String,
    pub mongo_actions: String,
}

pub fn language_selector(i: I18nOptions) -> I18n {
    match i {
        I18nOptions::ES => I18n {
            // intern: I18nOptions::ES,
            debug_json_string: "JSON Exportado".to_owned(),
            top_menu_config: "Configuración".to_owned(),
            top_http_toggle_sidebar: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_redis_toggle_sidebar: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_pg_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_pg_toggle_sidebar_tables: "Colapsar/Mostrar Tablas".to_owned(),
            top_kafka_toggle_sidebar_cluster: "Colapsar/Mostar Clústers".to_owned(),
            top_mongo_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_sqlite_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            top_mysql_toggle_sidebar_connections: "Colapsar/Mostrar Menú Lateral".to_owned(),
            http_btn_edit_ws_name: "Editar nombre del espacio de trabajo".to_owned(),
            http_btn_delete_ws: "Borrar espacio de trabajo".to_owned(),
            http_btn_update_request: "Actualizar".to_owned(),
            http_btn_send_request: "Lanzar Petición".to_owned(),
            http_send_to_http_performance: "Rendimiento de la Petición".to_owned(),
            pg_connection_host: "Host".to_owned(),
            pg_connection_port: "Puerto".to_owned(),
            pg_connection_user: "Usuario".to_owned(),
            pg_connection_password: "Contraseña".to_owned(),
            pg_connection_dbname: "Base de Datos".to_owned(),
            pg_btn_add_connection: "Anadir Conexión".to_owned(),
            pg_btn_connect: "Conectar".to_owned(),
            pg_btn_connected: "Conectado".to_owned(),
            pg_btn_load_tables: "Cargar Tablas".to_owned(),
            pg_btn_clean_table: "Limpiar Tabla".to_owned(),
            pg_btn_query: "Ejecutar".to_owned(),
            pg_btn_table_data_generator: "Generación de Datos".to_owned(),
            pg_btn_table_data_insertion: "Insertar Fila".to_owned(),
            pg_header_connection: "Conexión".to_owned(),
            pg_impossible_to_connect: "Imposible conectar con Postgres.".to_owned(),
            pg_connection: "Conectado.".to_owned(),
            pg_no_connection: "No conectado.".to_owned(),
            kafka_btn_add_connection: "Añadir Clúster".to_owned(),
            kafka_edit_cluster_name_label: "Nombre del Clúster".to_owned(),
            kafka_edit_cluster_host_label: "Host".to_owned(),
            kafka_edit_cluster_port_label: "Puerto".to_owned(),
            kafka_edit_cluster_save: "Guardar".to_owned(),
            kafka_edit_cluster_cancel: "Cancelar".to_owned(),
            kafka_btn_connect: "Conectar".to_owned(),
            kafka_btn_disconnect: "Desconectar".to_owned(),
            kafka_btn_show_brokers: "Brokers".to_owned(),
            kafka_btn_show_subscription: "Subscripción".to_owned(),
            kafka_btn_show_topics: "Topics".to_owned(),
            sqlite_btn_add_connection: "Abrir Archivo".to_owned(),
            sqlite_btn_table_data_generator: "Generación de Datos".to_owned(),
            sqlite_btn_clean_table: "Limpiar Tabla".to_owned(),
            sqlite_btn_table_data_insertion: "Insertar Fila".to_owned(),
            mongo_connection_host: "Host".to_owned(),
            mongo_connection_port: "Puerto".to_owned(),
            mongo_connection_user: "Usuario".to_owned(),
            mongo_connection_password: "Password".to_owned(),
            mongo_connection_srv: "SRV".to_owned(),
            mongo_actions: "Seleccionar Acción".to_owned(),
        },

        I18nOptions::EN => I18n {
            // intern: I18nOptions::EN,
            debug_json_string: "Exported JSON".to_owned(),
            top_menu_config: "Config".to_owned(),
            top_http_toggle_sidebar: "Collapse/Show Sidebar".to_owned(),
            top_redis_toggle_sidebar: "Collapse/Show Sidebar".to_owned(),
            top_pg_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_pg_toggle_sidebar_tables: "Collapse/Show Tables".to_owned(),
            top_kafka_toggle_sidebar_cluster: "Collapse/Show Clusters".to_owned(),
            top_mongo_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_sqlite_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            top_mysql_toggle_sidebar_connections: "Collapse/Show Sidebar".to_owned(),
            http_btn_edit_ws_name: "Edit workspace name".to_owned(),
            http_btn_delete_ws: "Delete workspace".to_owned(),
            http_btn_update_request: "Update".to_owned(),
            http_btn_send_request: "Send Request".to_owned(),
            http_send_to_http_performance: "Request Performance".to_owned(),
            pg_connection_host: "Host".to_owned(),
            pg_connection_port: "Port".to_owned(),
            pg_connection_user: "User".to_owned(),
            pg_connection_password: "Password".to_owned(),
            pg_connection_dbname: "Database".to_owned(),
            pg_btn_add_connection: "Add Connection".to_owned(),
            pg_btn_connect: "Connect".to_owned(),
            pg_btn_connected: "Connectec".to_owned(),
            pg_btn_load_tables: "Load Tables".to_owned(),
            pg_btn_clean_table: "Clean Table".to_owned(),
            pg_btn_query: "Run".to_owned(),
            pg_btn_table_data_generator: "Data Generation".to_owned(),
            pg_btn_table_data_insertion: "Insert Row".to_owned(),
            pg_header_connection: "Connection".to_owned(),
            pg_impossible_to_connect: "Impossible to connect with Postgres.".to_owned(),
            pg_connection: "Connected.".to_owned(),
            pg_no_connection: "No connected.".to_owned(),
            kafka_btn_add_connection: "Add Cluster".to_owned(),
            kafka_edit_cluster_name_label: "Cluster Name".to_owned(),
            kafka_edit_cluster_host_label: "Host".to_owned(),
            kafka_edit_cluster_port_label: "Port".to_owned(),
            kafka_edit_cluster_save: "Save".to_owned(),
            kafka_edit_cluster_cancel: "Cancel".to_owned(),
            kafka_btn_connect: "Connect".to_owned(),
            kafka_btn_disconnect: "Disconnect".to_owned(),
            kafka_btn_show_brokers: "Brokers".to_owned(),
            kafka_btn_show_subscription: "Subscription".to_owned(),
            kafka_btn_show_topics: "Topics".to_owned(),
            sqlite_btn_add_connection: "Open File".to_owned(),
            sqlite_btn_table_data_generator: "Data Generation".to_owned(),
            sqlite_btn_clean_table: "Clean Table".to_owned(),
            sqlite_btn_table_data_insertion: "Insert Row".to_owned(),
            mongo_connection_host: "Host".to_owned(),
            mongo_connection_port: "Port".to_owned(),
            mongo_connection_user: "User".to_owned(),
            mongo_connection_password: "Password".to_owned(),
            mongo_connection_srv: "SRV".to_owned(),
            mongo_actions: "Select Action".to_owned(),
        },
    }
}
